= Dependencies

To get started with modding of satisfactory you'll need multiple other
pieces of software downloaded and set up first.

Don't worry, we'll guide you through each step of downloading and
installing these dependencies.

== Satisfactory

This should be pretty straightforward. Simply buy, download, and install
Satisfactory from the Epic Games Launcher. Launch the game to ensure all
files get set up correctly.

== Visual Studio

Visit the website of https://visualstudio.microsoft.com/de/downloads/[MS Visual Studio]
and download the version you want.

Most of the time you want to use the Community version because it's free of charge.

Then open the installer and select the packages "C++ Desktopdevelopment"
and "Gamedevelopment with C++".

Now install the IDE.

== Unreal Engine 4 (Custom Engine)

Because the game uses a modified version of the engine, we modder to need to use a modified version.
But a more important point for is that we need to compile the native code dynamically.
Coffee Stain Studios does not wich causes quite some limitations.
The bootstrapper here is now use to hook the dynamic linker and use the by CSS provided `.pdb`
to link the monolithic built game and our dynamic build mods.
The custom engine for modding has also some other changes needed to workaround some technical limitations.

For installing it, just visit the https://github.com/SatisfactoryModdingUE/UnrealEngine/releases[GitHub Releases Page]
and download the installer for the version most suitable for your needs.
Most of the time you just simply use the latest version.

[TIP]
====
Download the .exe file wich is a installer for the Engine.
We highly reccomend using the installer instead of building the Engine itself
unless you rly want to work on the engine.
====

== Wwise

Visit https://wwise.com/[Wwise.com] and click on the `+Get Wwise+` ->
`+download Wwise+` button in the upper right corner. Now the website
should ask you to log in. Click on `+Sign in+` and follow the given
steps. After you finished downloading Wwise, open the installer and
start with installing the WWise launcher.

== Satisfactory Mod Loader

Just make sure you have a working "normal" modloader version up and running
so you can actually test your mod.
