= Required Software

To get started with modding Satisfactory,
you'll need multiple other pieces of software installed first.
Don't worry, we'll guide you through each step
of downloading and installing these dependencies.

This can be a very lengthy process,
so if you take a break,
make a note of where you left off so it's easier to resume later.

Beware that the modding environment can take up a lot of space
once everything is installed and built - 30+ GB is possible.
Keep this in mind when deciding where put all your files
- don't keep them on a drive with very little space left. 

== Before you Begin

Make sure you've read the starting information on the
xref:Development/BeginnersGuide/index.adoc[Getting Started title page]
to learn important information about how to use these docs.

[IMPORTANT]
====
Are you a returning Satisfactory modder who already has a past modding environment set up?
Make sure to follow the
xref:Development/UpdatingToNewVersions.adoc[_Updating your Mod_]
guide before following these directions.
====

== Satisfactory

This one should be pretty straightforward, and odds are, you've already done it.
Simply buy, download, and install Satisfactory from the
https://store.epicgames.com/en-US/p/satisfactory[Epic Games Store]
or https://store.steampowered.com/app/526870/Satisfactory/[Steam].
Launch the game at least once to ensure all files get set up correctly.

== Visual Studio

Visit the https://visualstudio.microsoft.com/downloads/[Microsoft Visual Studio downloads page]
and select the button for Visual Studio 2022 Community, which is free of charge.

If you already have Visual Studio installed,
you'll need to run installer again and follow the steps below to modify your existing installation.

After the installer has downloaded, run it and agree to any authorization prompts you receive along the way.
Once you are prompted to install Visual Studio 2022
you have two options for selecting the relevant components.

[id="ImportConfiguration"]
=== Option 1: Import an Installer Configuration

If the installer took you directly to the Workflow or Component selection screen
you'll have to use the smaller X button in the top right to close out of that prompt first.

Instead of clicking "Install" next to Visual Studio 2022,
click the 'More' dropdown and select `Import Configuration`.
If the option does not appear, make sure that your existing installation is not "pending"
by allowing it to finish installing.

// cspell:ignore vsconfig
Download link:{attachmentsdir}/BeginnersGuide/dependencies/SML.vsconfig[this configuration file]
and select it in the installer's prompt.
Next, press `Review details` and continue with the installation.

[id="ManuallySelectComponents"]
=== Option 2: Manually Select Components

From the "Workloads" tab, select:

- `Desktop & Mobile` > `Desktop development with {cpp}`
- `Gaming` > `Game development with {cpp}`.

You might have to scroll a bit to find them.

Next, from the "Individual Components" tab,
search for and select:

- `MSVC v143 - VS 2022 C++ x64/x86 build tools (v14.34-17.4)`
- `.NET 6.0 Runtime (Long Term Support)`
- `.NET Framework 4.8.1 SDK`

=== While Visual Studio Installs

Downloading and installing Visual Studio can take a while.
We advise you to find some lizard doggos to pet while you wait,
or work on some of the other install steps below.

[TIP]
====
An alternative to Visual Studio which is very popular among {cpp} modders is
https://www.jetbrains.com/lp/rider-unreal/[Rider for Unreal Engine].
If you consider using it, make sure you still have Visual Studio and the necessary VS-{cpp} packages installed,
as they are used by Unreal's own compiler systems,
and make sure to use the `.sln` project model.
====

[id="ClangToolchain"]
== Clang Toolchain for Linux Dedicated Server Support

Satisfactory's dedicated servers typically run on Linux.
Cross-compiling from Windows to Linux requires
the compatible version of Unreal Engine specific CLang Toolchain to be installed
prior to building for Linux Dedicated Servers.
The download link for these files can be found on the Unreal documentation page for 
https://dev.epicgames.com/documentation/en-us/unreal-engine/linux-development-requirements-for-unreal-engine?application_version=5.3#nativetoolchain[Cross-Compiling for Linux].

Currently, Satisfactory uses Unreal Engine 5.3.2 with custom changes provided by Coffee Stain Studios.
Therefore, the Cross-Compile Toolchain version required is `-v22` or `clang-16.0.6-based`.

Download the correct Cross-Compile Toolchain from the link above and run it to install the relevant files.
The default options that the installer offers are fine.

[id="CustomEngine"]
== Custom Unreal Engine Version

Because Satisfactory uses a modified version of Unreal Engine,
we modders need to be using that same version as well to develop our mods.

If you already have Unreal Engine installed for something else,
that installation **will not work** for Satisfactory modding
- you will still have to follow the below steps.

=== Link your GitHub as an Epic Games Developer Account

For this step, you'll need a GitHub account,
so https://github.com/signup[sign up for one]
if you don't already have one.

Once you've got a GitHub account,
you'll need to register it with Epic Games and join the Epic Games GitHub organization to be able to download this special version.
Directions on how to link so can be found
https://www.unrealengine.com/en-US/ue-on-github[here].

If the page says, "Sorry, the service is temporarily unavailable. Please try back later."
try turning off any ad-blockers or content filters you may have enabled and refreshing the page without cache (Ctrl+Shift+R).

You will probably have to check your email and confirm from there,
as well as making sure you're logged into your linked GitHub account when you follow the upcoming link.

Verify this step has worked by visiting this repository link:
https://github.com/EpicGames/UnrealEngine/
(or https://github.com/EpicGames-Mirror-A/UnrealEngine/ since June 2024)
If it worked, you will see a private GitHub repository.
If it didn't work, you'll get a 404 page, so try the other link.
If neither link works, try again in a few minutes and make sure you didn't miss any steps in Unreal's instructions.

Once you're sure it works, close that browser tab - we don't need any files from this repository.
Visiting there was just to verify that you have access.

[id="UnrealLinker"]
=== Link Your GitHub Account to Our Repository

In addition to the changes Coffee Stain has made to Unreal Engine,
the modding community has also applied some engine changes of our own.

You'll have to link your account through a tool we created
in order to view our repository and download the required files.
To use the tool, visit the following link: https://linker.ficsit.app/link

After the linking process is complete you should be redirected to the engine GitHub repository.

After you have access to the custom engine repository it's safe to remove the application's permissions
by visiting your https://github.com/settings/connections/applications/bdde02a7b3318bf2b84d[GitHub settings page].

[TIP]
====
If you're curious, you can find the source code for the tool used to perform the linking process
https://github.com/satisfactorymodding/unreal-linker[here].
====

=== Download the Custom Engine

Next, navigate to the Satisfactory Modding custom Unreal Engine GitHub project to download some installer files.

The below box will contain a link to the specific release that you should download.
It's imperative that you download the correct engine for the version of the game you're modding
or you will have to repeat a large amount of the setup process again.

// When updating the below, remember to update StaterProjectViaClone.adoc, StarterProjectViaZip.adoc, and dependencies.adoc (engine)
====
This is the *archived v3.10.0* version of the docs.

If you want to develop mods for a newer release,
you should follow the
link:https://docs.ficsit.app/satisfactory-modding/latest/index.html[latest docs branch].

To develop for 3.10.0, use this engine version:
https://github.com/satisfactorymodding/UnrealEngine/releases/tag/5.3.2-css-66
====

Download the following files from the release linked above:

- `UnrealEngine-CSS-Editor-Win64-1.bin`
- `UnrealEngine-CSS-Editor-Win64-2.bin`
- `UnrealEngine-CSS-Editor-Win64.exe`

Save all 3 files in the same folder,
and make sure that their names are _exactly the same as listed above_
otherwise the installer will not work.

[WARNING]
====
If you see a "404 This is not the web page you are looking for" error,
then you didn't finish linking your account.
The page is _not_ dead, this is what GitHub displays as a security measure
when someone tries to access a private repo and is not part of the correct organization.

Check for emails from both Epic and GitHub, and be sure that you followed the above steps.
You can verify that you've correctly joined the GitHub organization by checking for "EpicGames" on the
https://github.com/settings/organizations[GitHub Account Organizations page].
If your GitHub account is already listed as linked on the Epic Games page you can unlink and relink it re-send the GitHub organization invitation.

You also must have used the link:#UnrealLinker[Unreal Linker] tool described above to link your GitHub account to our repository.
====

=== Install the Custom Engine

Once all files have finished downloading,
run the `.exe` and follow through its prompts
to install the custom Unreal Engine version and corresponding Editor.

[IMPORTANT]
====
Are you a returning Satisfactory modder who already has a past modding environment set up?
Make sure to back up your past engine version as described in the
xref:Development/UpdatingToNewVersions.adoc[_Updating your Mod_]
guide before following these directions.
====

[WARNING]
====
If the installer asks you to select the folder with the next medium files or insert the next disc,
select the folder that contains the `.bin` files you downloaded.

Additionally, make sure to name the downloaded files exactly as stated above,
otherwise the installer may be unable to locate the `.bin` files.
====

This install process, and opening Unreal for the first time afterwards, can take some time.
Don't worry about opening Unreal yet, though.
It will probably ask you to compile things you haven't properly set up yet.

=== Install the Visual Studio Extension (Optional)

Once the installer is done you can optionally install a Visual Studio extension shipped with the Editor.
This extension allows you to directly open {cpp} files from the Unreal editor.

Navigate to where you installed the Editor, which is likely
`C:\Program Files\Unreal Engine - CSS\`,
then navigate to the folder `\Engine\Extras\UnrealVS\`.
Open the sub folder for the version of Visual Studio you have installed (probably 2022)
// cspell:ignore vsix
and run the `.vsix` installer.

== Wwise

Wwise is a sound engine used by Coffee Stain,
and in order to develop mods,
you'll need to install and integrate Wwise with your mod project,
even if you do not plan to modify sounds.

Visit https://www.audiokinetic.com/en/download/[Wwise] and click on the
`+Download Audiokinetic Launcher+` button.
Clicking the button will probably redirect you to a sign in page.
Create an account if you don't have one yet, or sign in, to download and run the installer.

After the installer is complete it should open the launcher for you.

In the launcher's left sidebar, select the topmost `Wwise` section
(note: not the "Wwise Audio Lab" section).
Under the "INSTALL A NEW VERSION" heading,
click the `Latest` drop-down and change it to `All`.
Select `2022.1` from the "Major" dropdown.
Select version `2022.1.10.8393` from the "Version" dropdown.
Click `Install`.

[WARNING]
====
Watch out - most older versions of Wwise don't have support for Unreal Engine 5, which this project needs.
Newer versions of Wwise __might__ work,
but they are likely to have other incompatible changes that will break the setup process.

**Try to download the exact Wwise version mentioned above**.
If you don't see it,
try any other version starting with `2022.1.10`, preferring newer versions,
or asking for help on the Discord.
====

Once presented with options on what to install, select:

// Inline HTML to make checkmarks green
// https://docs.asciidoctor.org/asciidoc/latest/pass/pass-block/
// https://docs.asciidoctor.org/asciidoc/latest/pass/pass-macro/
[pass]
<style type="text/css"> .green-check { color: greenyellow; } </style>

* _Packages_
** pass:[<span class="green-check">✔</span>] Authoring
** pass:[<span class="green-check">✔</span>] SDK (C++)
* _Deployment Platforms_
** pass:[<span class="green-check">✔</span>] Linux
** _Microsoft_
*** _Windows_
**** pass:[<span class="green-check">✔</span>] Visual Studio 2019
**** pass:[<span class="green-check">✔</span>] Visual Studio 2022

If anything is selected by default, do not uncheck them. They are required for Visual Studio to work.

Click `Next` (you may need to scroll down to see the button).
You don't need to add any plugins,
so press `Select None` in the top right then `Install` in the bottom left to begin the installation process.
Accept the terms and conditions prompts that appear along the way.

== Satisfactory Mod Manager

xref:index.adoc#_satisfactory_mod_manager_aka_smm[Satisfactory Mod Manager]
is a powerful tool that automatically install the correct versions of mod dependencies for you.
Basically all end users will be using this tool to install your mods.

As a developer, you can use it to install the https://ficsit.app/mod/SML[Satisfactory Mod Loader (SML)] mod
and install other mods to test with.

Alternatively, once your modding environment is set up,
you can use Alpakit to automatically build and install SML.
This process will be explained on the next page.

== Next Steps

The last dependency to obtain is a copy of the modding Starter Project.
Check out the xref:Development/BeginnersGuide/StarterProject/ObtainStarterProject.adoc[next section]
for directions on how to obtain it.
