
= Dependencies

To get started with modding Satisfactory,
you'll need multiple other pieces of software installed first.
Don't worry, we'll guide you through each step
of downloading and installing these dependencies.

This can be a very lengthy process,
so if you have to work on something else,
make a note of where you left off so it's easier to resume.

Beware that the modding environment can take up a lot of space
once everything is installed and built - 30+ GB is possible.
Keep this in mind when deciding where put all your files
- don't keep them on a drive with very little space left. 

[TIP]
====
If you'd prefer a different format of guide, you can find a video guide
https://www.youtube.com/watch?v=-HVw6-3Awqs[here].
**As of SML 3.0.0, these video tutorials are out of date,
but some of the concepts will still carry over.**
If you get stuck in the video tutorials, return here and follow these guides instead.
Be sure to read over the steps here as well to be sure you're doing things correctly.
====

== Before you Begin

Make sure you've read the starting information on the
xref:Development/BeginnersGuide/index.adoc[Getting Started title page]
to learn important information about how to use these docs.

== Satisfactory

This one should be pretty straightforward, and odds are, you've already done it.
Simply buy, download, and install Satisfactory from the Epic Games Launcher or Steam.
Launch the game at least once to ensure all files get set up correctly.

== Visual Studio

Visit the https://visualstudio.microsoft.com/downloads/[Microsoft Visual Studio downloads page]
and select the button for Visual Studio 2022 Community, which is free of charge.

If you already have Visual Studio installed,
you can run the installer again and still follow the steps below to modify your existing installation.

After the installer has downloaded, run it and agree to any authorization prompts you receive along the way.
Once you are prompted to install Visual Studio 2022
you have two options for selecting the relevant components.

[id="ImportConfiguration"]
=== Option 1: Import an Installer Configuration

If the installer took you directly to the component selection screen
you'll have to use the smaller X button in the top right to close out of that prompt first.

Instead of clicking "Install" next to Visual Studio 2022,
click the 'More' dropdown and select `Import Configuration`.

// cspell:ignore vsconfig
Download link:{attachmentsdir}/BeginnersGuide/dependencies/SML.vsconfig[this configuration file]
and select it in the installer's prompt.
Next, press `Review details` and continue with the installation.

[id="ManuallySelectComponents"]
=== Option 2: Manually Select Components

From the "Workloads" tab select
"Desktop & Mobile > Desktop development with {cpp}"
and "Gaming > Game development with {cpp}".
You might have to scroll a bit to find them.

Next, from the "Individual Components" tab,
search for and select `MSVC v143 - VS2022 C++ x64/x86 build tools (v14.34-17.4)`

You will also need the .NET Framework SDK version 4.8 or higher (but not Core/v5).
If you do not know if you have the .NET Framework SDK,
the VS installer should provide an option to install it.
It is recommended to tick it.

=== While Visual Studio Installs

Downloading and installing Visual Studio can take a while.
We advise you to find some lizard doggos to pet while you wait,
or work on some of the other install steps below.

[TIP]
====
An alternative to Visual Studio which is very popular among {cpp} modders is
https://www.jetbrains.com/lp/rider-unreal/[Rider for Unreal Engine].
If you consider using it, make sure you still have the necessary VS-{cpp} packages installed.
====

////
dedi-docs
== Clang Toolchain for Linux Dedicated Server Support

Satisfactory's dedicated servers typically run on Linux.
Cross-compiling from Windows to Linux requires the compatible version of Unreal Engine specific CLang Toolchain to be installed prior to building for Linux Dedicated Servers.
The download link for these files can be found on the Unreal documentation page for 
https://docs.unrealengine.com/5.0/en-US/linux-development-requirements-for-unreal-engine/[Cross-Compiling for Linux].

Currently, Satisfactory uses Unreal Engine 5.1.1 with custom changes provided by Coffee Stain Studios.
Therefore, the toolchain version required is `-v20` or `clang-13.0.1-based`.

// UE5.2 Dedi //Currently, Satisfactory uses Unreal Engine 5.2.1 with custom changes provided by Coffee Stain Studios.
// UE5.2 Dedi //Therefore, the toolchain version required is `-v21` or `clang-15.0.1-based`.

Download the toolchain from the link above and run it to install the relevant files.
The default options that the installer offers are fine.
dedi-docs
////

[id="CustomEngine"]
== Custom Unreal Engine Version

Because Satisfactory uses a modified version of Unreal Engine,
we modders need to be using that same version as well to develop our mods.

If you already have Unreal Engine installed for something else,
that installation **will not work** for Satisfactory modding
- you will still have to follow the below steps.

=== Link your GitHub as an Epic Games Developer Account

For this step, you'll need a GitHub account,
so https://github.com/signup[sign up for one]
if you don't already have one.

Once you've got a GitHub account,
you'll need to register it with Epic Games and join the Epic Games GitHub organization to be able to download this special version.
Directions on how to link so can be found
https://www.unrealengine.com/en-US/ue-on-github[here].

If the page says, "Sorry, the service is temporarily unavailable. Please try back later."
try turning off any ad-blockers or content filters you may have enabled and refreshing the page without cache (Ctrl+Shift+R).

You will probably have to check your email and confirm from there,
as well as making sure you're logged into your linked GitHub account when you follow the upcoming link.

[id="UnrealLinker"]
=== Link Your GitHub Account to Our Repository

In addition to the changes Coffee Stain has made to Unreal Engine,
the modding community has also applied engine some changes of our own.

You'll have to link your account through a tool we created in order to view our repository and download the required files.
To use the tool, visit the following link: https://linker.ficsit.app/link

After the linking process is complete you should be redirected to the engine GitHub repository.

After you have access to the custom engine repository it's safe to remove the application's permissions
by visiting your https://github.com/settings/connections/applications/bdde02a7b3318bf2b84d[GitHub settings page].

[TIP]
====
If you're curious, you can find the source code for the tool used to perform the linking process
https://github.com/satisfactorymodding/unreal-linker[here].
====

=== Download the Custom Engine

Next, go to the
https://github.com/satisfactorymodding/UnrealEngine/releases[Satisfactory Modding Unreal Engine project releases page]
and download some files from the latest release:

- `UnrealEngine-CSS-Editor-Win64-1.bin`
- `UnrealEngine-CSS-Editor-Win64-2.bin`
- `UnrealEngine-CSS-Editor-Win64.exe`

[WARNING]
====
If you see a "404 This is not the web page you are looking for" error,
then you didn't finish linking your account.
The page is _not_ dead, this is what GitHub displays as a security measure
when someone tries to access a private repo and is not part of the correct organization.

Check for emails from both Epic and GitHub, and be sure that you followed the above steps.
You can verify that you've correctly joined the GitHub organization by checking for "EpicGames" on the
https://github.com/settings/organizations[GitHub Account Organizations page].
If your GitHub account is already listed as linked on the Epic Games page you can unlink and relink it re-send the GitHub organization invitation.

You also must have used the link:#UnrealLinker[Unreal Linker] tool described above to link your GitHub account to our repository.
====

=== Install the Custom Engine

Once all files have finished downloading,
run the `.exe` and follow through its prompts
to install the custom Unreal Engine version and corresponding Editor.

[WARNING]
====
If the installer asks you to select the folder with the next medium files,
select the folder that contains the `.bin` files you downloaded.

Additionally, make sure to name the downloaded files exactly as stated above,
otherwise the installer may be unable to locate the `.bin` files.
====

This install process, and opening Unreal for the first time afterwards, can take some time.
Don't worry about opening Unreal yet, though.
It will probably ask you to compile things you haven't properly set up yet.

=== Install the Visual Studio Extension (Optional)

Once the installer is done you can optionally install a Visual Studio extension shipped with the Editor.
This extension allows you to directly open {cpp} files from the Unreal editor.

Navigate to where you installed the Editor, which is likely
`C:\Program Files\Unreal Engine - CSS\`,
then navigate to the folder `\Engine\Extras\UnrealVS\`.
Open the sub folder for the version of Visual Studio you have installed (probably 2022)
// cspell:ignore vsix
and run the `.vsix` installer.

== Wwise

Wwise is a sound engine used by Coffee Stain,
and in order to develop mods,
you'll need to install and integrate Wwise with your mod project,
even if you do not plan to modify sounds.

Visit https://www.audiokinetic.com/products/wwise/[Wwise] and click on the
`+Get Started+` -> `+Download Wwise+` button in the upper right corner.
Click the download button, which will ask you to sign in.
Create an account if you don't have one yet, or sign in, to download the launcher.
After you finished downloading Wwise, open the installer.

After the installer is complete it should open the Wwise launcher for you.
In the launcher, select `WWISE` from the sidebar.
Click the `Latest` drop-down and change it to `All`.
Select `2022.1` from the next dropdown.
Select version `2022.1.3.8179` from the final dropdown.
Click `Install`.

[WARNING]
====
Watch out - most older versions of Wwise don't have support for Unreal Engine 5, which this project needs.

If you don't see this exact Wwise version,
try any other version starting with `2022.1`, preferring newer versions,
or asking for help on the Discord.
====

Once presented with options on what to install, select:

* _Packages_
** Authoring
** SDK (C++)
* _Deployment Platforms_
// dedi-docs ** Linux
** _Microsoft_
*** _Windows_
**** Visual Studio 2019
**** Visual Studio 2022

Click `Next` (you may need to scroll down to see the button).
You don't need to add any plugins,
so press `Deselect All` then `Install` in the bottom left to begin the installation process.
Accept the terms and conditions prompts that appear along the way.

== Starter Project

The SML development team has an Unreal project prepared
that comes pre-installed with Satisfactory Mod Loader,
placeholder assets for base game content,
and some useful developer plugins.

Within this 'Starter Project,' you can develop as many mods as you like
while still keeping their files separate,
which will be covered later in the docs.

If you are familiar with version control software (ex. Git),
we suggest that you https://github.com/satisfactorymodding/SatisfactoryModLoader/[clone the repo],
which drastically simplifies the process of updating the files later when the game updates.
Check on the Discord to find out which branch to clone,
although it's most likely `master`.
The Project Setup page (up next) will tell you where to clone it.

If you're not familiar with version control,
xref:Development/BeginnersGuide/CreateGitRepo.adoc[now is a great time to learn]!
Using Version Control Software (VCS) is a great skill to have for developers
and will greatly help with updating your project in the future,
as well as protect you from losing your mod sources if you upload them to a hosting website like GitHub.

However, if you'd just like to get started modding,
you can download a zip of the Starter Project
from the Satisfactory Modding GitHub,
or directly via https://github.com/satisfactorymodding/SatisfactoryModLoader/archive/refs/heads/master.zip[this link].

Don't do anything with the downloaded files yet - this will be covered on the next page, Project Setup.

== Satisfactory Mod Manager

xref:index.adoc#_satisfactory_mod_manager_aka_smm[Satisfactory Mod Manager]
offers a convenient developer mode that
automatically installs the correct version of SML and helps manage mod files for you.
To enable it, change your selected profile to `development`.
If you're using Satisfactory Mod Manager,
you can skip the below steps and move on to the next page of the tutorial. 

If you're not using the mod manager, you can follow the
xref:ManualInstallDirections.adoc[manual install directions]
to get the relevant files set up.
Alternatively, once your modding environment is set up,
you can use Alpakit to automatically build and install SML.
This process is covered on the next page.

== Next Steps

Now that all the dependencies are installed, you can move onto
xref:Development/BeginnersGuide/project_setup.adoc[setting up the project].
