
= Dependencies

To get started with modding Satisfactory, you'll need multiple other pieces of software installed first.

Don't worry, we'll guide you through each step of downloading and installing these dependencies.

This can be a very lengthy process, so if you have to work on something else, make a note of where you left off so it's easier to resume.

Beware that the modding environment can take up a lot of space once everything is installed and built - 30+ GB is possible. Keep this in mind when deciding where put all your files - don't keep them on a drive with very little space left. 

[TIP]
====
If you'd prefer a different format of guide, you can find a video guide
https://www.youtube.com/watch?v=-HVw6-3Awqs[here].
**As of SML 3.0.0, these tutorials are out of date,
but some of the concepts will still carry over.**
If you get stuck in the video tutorials, return here and follow these guides instead.
Be sure to read over the steps here as well to be sure you're doing things correctly.
====

== Satisfactory

This one should be pretty straightforward, and odds are, you've already done it. Simply buy, download, and install Satisfactory from the Epic Games Launcher or Steam.
Launch the game at least once to ensure all files get set up correctly.

== Visual Studio

Visit the https://visualstudio.microsoft.com/downloads/[Microsoft Visual Studio downloads page] and download the version you want.
We suggest either Visual Studio 2019 or 2017 Community, because they're free of charge. It is important that if you use 2019 you still install the 2017 compilers.

Run the installer, and agree to prompts you receive along the way. Select the packages "{cpp} Desktop development" and "Game development with {cpp}". You might have to scroll a bit to find them.

If you already have Visual Studio installed, you can run the installer again and choose `Modify` to select these two packages and add them to your installation.

Continue through the rest of the prompts to install Visual Studio. Downloading and installing Visual Studio can take a while, so we advise you to find some lizard doggos to pet while you wait, or working on some of the other install steps below.

[TIP]
====
An alternative to Visual Studio which is very popular among {cpp} modders is https://www.jetbrains.com/lp/rider-unreal/[Rider for Unreal Engine].
If you consider using it, make sure you still have the necessary VS-{cpp} packages installed.
====

== Unreal Engine 4 (Custom Engine)

Because Satisfactory uses a modified version of Unreal Engine, we modders need to be using that same version as well to develop our mods.

You'll need to register your GitHub account with Epic Games to be able to download this special version. Directions on how to do so can be found https://www.unrealengine.com/en-US/ue4-on-github[here].

If the page says, "Sorry, the service is temporarily unavailable. Please try back later." try turning off any adblockers or content filters you may have enabled and refreshing the page without cache (Ctrl+Shift+R).

You will probably have to check your email and confirm from there, as well as making sure you're logged into your linked GitHub account when you follow the upcoming link.

Once you've done that, go to the https://github.com/SatisfactoryModdingUE/UnrealEngine/releases[Satisfactory Modding Unreal Engine project] and download `UnrealEngine-CSS-Editor-Win64.exe`, then run it to install the Unreal Engine editor for this custom version.

[WARNING]
====
If you see a "404 This is not the web page you are looking for" error, then you didn't finish linking your account. Check for emails from both Epic and GitHub, and be sure that you followed the above steps. The page is _not_ dead, this is what GitHub displays as a security measure when someone tries to access a private repo.
====

This install process, and opening Unreal for the first time afterwards, can take some time. Don't worry about opening Unreal yet though. It will probably ask you to compile things you haven't properly set up yet.

Once the installer is done, you'll also need to install a Visual Studio extension shipped with the Editor. Navigate to where you installed the Editor, probably something like `C:\Program Files\Unreal Engine - CSS\`, and then navigate to the folder `\Engine\Extras\UnrealVS\`. Open the sub folder for the version of Visual Studio you have installed (probably 2019) and run the .vsix installer to install the Unreal Visual Studio extension, which will help with debugging.

== Wwise

Wwise is a sound engine used by Coffee Stain,
and in order to develop mods,
you'll need to install and integrate Wwise with your mod project.

Visit https://wwise.com/[Wwise.com] and click on the
`+Get Wwise+` -> `+Download Wwise+` button in the upper right corner.
Click the download button, which will ask you to sign in.
Create an account if you don't have one yet, or sign in, to download the launcher.
After you finished downloading Wwise, open the installer.

Select `WWISE` from the top bar, and select version `2021.1.0.7575`
(you might need to change the left dropdown to `All` to do this), then press `Install`.
Once presented with options on what to install,
make sure that `Authoring` and `SDK (C++)` packages are checked on the left,
and that `Apple` -> `MacOS` and
`Microsoft` -> `Windows` -> `Visual Studio 2017`
and `Visual Studio 2019` are selected, then press `Next`.
You don't need to add any plugins,
so just press `Install` to skip in the bottom left to begin the installation process.
Accept any authentication prompts that appear along the way.

[WARNING]
====
Make sure that you selected the correct version of Wwise.
It's easy to choose the wrong version by accident.
====

[TIP]
====

if you are getting a checksum error during Wwise integration, installing any other version should fix the problem

====

== Starter Project

To get started developing your mod, start off with the Starter Project as a base.
You can find it on the Satisfactory Modding GitHub, or download it directly via 
https://github.com/satisfactorymodding/SatisfactoryModLoader/archive/refs/heads/master.zip[this link].

The Starter Project itself is contained in `FactoryGame.uproject`,
and this download contains the relevant SML-related plugins already loaded.
Don't do anything with the downloaded zip file yet - this will be covered on the next page, Project Setup.

If you are familiar with version control software, we suggest you
https://github.com/satisfactorymodding/SatisfactoryModLoader/[clone the repo instead],
which simplifies the process of updating your project later.
Check on the discord to find out which branch to clone,
although it's most likely `master`.

== Satisfactory Mod Loader

xref:index.adoc#_satisfactory_mod_manager_title_refaka_smm[Satisfactory Mod Manager]
offers a convenient developer mode that
automatically installs the correct version of SML and helps manage mod files for you.
To enable it, change your selected profile to `development`.
If you're using Satisfactory Mod Manager,
you can skip the below steps and move on to the next page of the tutorial. 

If you're not using the mod manager, you'll need to follow the
xref:ManualInstallDirections.adoc[manual install directions]
to get the relevant files set up.

Alternatively, once your modding environment is set up,
you can use Alpakit to automatically build and install SML.

Now that all the dependencies are installed, you can move onto xref:Development/BeginnersGuide/project_setup.adoc[setting up the project].