= Satisfactory Modding Documentation

== Basics

Welcome to the Satisfactory Modding Documentation site! 

Here you can find lots of information regarding modding
https://www.satisfactorygame.com/[Satisfactory],
the factory-building sim by https://www.coffeestainstudios.com/games/[Coffee Stain Studios] (CSS).
Modding for Satisfactory is more established than you might think given how long the game has been out.
There are already https://ficsit.app/[over 600 mods] released
and we maintain in-depth documentation on how you can create your own.

In this page, we will provide some surface level information for both mod users and developers.

[TIP]
====
We suggest you join our https://discord.ficsit.app[Discord Server]
to get support and chat with fellow mod users and developers!
====

== For Users

If you'd like to get started using mods, this section is for you.

=== Welcome Guide

If this is your first time modding Satisfactory,
check out the xref:ForUsers/Welcome.adoc[Welcome to the Community] guide to get started with mods quickly.

=== Satisfactory Mod Repository [.title-ref]#(aka. SMR aka. ficsit.app aka. FICSIT Augmentation Database)#

The Satisfactory Mod Repository (SMR) is the most extensive collection of mods made for Satisfactory.
It's easy to upload a mod of your own or write a guide for other users.
Uploaded content is tested for malware and such before it is approved for download.
Visit https://ficsit.app/[ficsit.app] to see it for yourself!

=== Satisfactory Mod Manager [.title-ref]#(aka. SMM)#

The Satisfactory Mod Manager allows the end user to easily install mods, their dependencies, and the mod loader.
It connects to https://ficsit.app/[SMR], allowing for quick and easy installation of all mods.

====
Learn how to install and use the mod manager on the
xref:ForUsers/SatisfactoryModManager.adoc[Using the Mod Manager] page.
====

We highly recommend using Satisfactory Mod Manager to install mods as it makes using mods that much easier.
However, if you _really_ don't want to use the launcher,
directions for manual installation can be found xref:ManualInstallDirections.adoc[here].

== For Developers

If you'd like to write a mod of your own, this section is for you.

Satisfactory mods can be written in Unreal Blueprint or {cpp}.
Some community created libraries also allow writing mods
with JSON files xref:Development/BeginnersGuide/overwriting.adoc#_contentlib[(ContentLib)]
// cspell:ignore tweakit
or Lua xref:Development/BeginnersGuide/overwriting.adoc#_tweakit[(TweakIt)].

If you're looking to write your own mods, we suggest you start with
making blueprint mods first rather than C++ mods.
Check out the xref:Development/BeginnersGuide/index.adoc[Getting Started Guide]
and consider picking up the `Aspiring Modder` role in the "Channels & Roles" section of our https://discord.ficsit.app[Discord].

If you're looking to make models, it's best to learn how to put a mod together first.
Once you've completed the `Buildable` step in `Beginners Guide`, then check out our xref:Development/Modeling/index.adoc[Modeling Guide].

=== Uploading Your Mod to SMR

After you've finished your mod (or at least its first version), you might want to upload it to https://ficsit.app/[SMR]. Read the dedicated docs page to know more on how to do that xref:UploadToSMR.adoc[here]!

== Archived Forums

The community used to have a Discourse-powered forums website for modding discussion,
but it has since been archived due to low usage.
You can find the archives https://forums.ficsit.app/[here].

== Contributing

You can find information on how to contribute to the docs
https://github.com/satisfactorymodding/Documentation#contributing[in the github repo's readme].

== Modding Technologies

If you'd like to learn more about how modding works internally, this is the section for you.

=== Satisfactory Mod Loader [.title-ref]#(aka. SML)#

Satisfactory Mod Loader (SML) provides a framework that makes it easier for mods to be able 
to load into systems provided by the game, and to interact with each other.
It also provides many helper features to assist in mod development.
Due to how CSS has configured Satisfactory,
it is possible to make mods that do not require SML to function,
however this is rarely done in practice.

=== Alpakit

Alpakit is an Unreal Engine Plugin created by Mircea and other contributors
allowing you to easily cook and package your mod for deployment and distribution.
It is also able to directly install it into your game installation for you.
Behind the scenes, it uses Unreal Pak and some custom code to accomplish this.
