= Satisfactory Modding Documentation

== Basics

Welcome to the Satisfactory Modding Documentation site! 

Here you can find lots of information regarding modding https://www.satisfactorygame.com/[Satisfactory], the factory-building sim by https://www.coffeestainstudios.com/games/[Coffee Stain Studios]. Modding for Satisfactory is more established than you might think given how long the game has been out. There are already https://ficsit.app/[numerous mods] released, and there are multiple methods by which you can develop new mods yourself. 

In this doc we will mainly focus on the general community, ficsit.app and SML.


[TIP]
====
If you want to take part in this great community, we recommend you to
join our https://discord.gg/xkVJ73E[Discord Server] or the
https://forums.ficsit.app/[Ficsit.app Forums].
====

== Modding Technologies

=== Satisfactory Mod Repository [.title-ref]#(aka. SMR aka. ficsit.app aka. FICSIT Augmentation Database)#

The Satisfactory Mod Repository (SMR) is the most extensive collection of mods made for Satisfactory. It’s easy to upload a mod of your own or write a guide for other users. Uploaded content gets tested for malware and other potential issues. Visit https://ficsit.app/[ficsit.app] to learn more.

=== Satisfactory Mod Launcher

The Satisfactory Mod Launcher allows the end user to easily install mods, there dependecies aswell as the bootstrapper and mod loader.
It connects to https://ficsit.app/[SMR] allowing for a easy installation process.

Check it out on https://github.com/satisfactorymodding/SatisfactoryModLauncher/releases[GitHub]

[TIP]
====
We highly reccomend you to use this launcher for installing mods.
====

=== Satisfactory Mod Bootstrapper

The Satisfactory Mod Bootstrapper is the holy heart of C++ Modding for Satisfactory.
Due to technical limitations custom build Unreal Engine C++ module can't get linked normaly by the windows dynamic linker into the game because it is build monolithic.
This also means that some functions are simply not build into the game were we rly on accessor functions to allow C++ mods to use these functions anyway. (f.e. USceneComponent::SetVisibility)
In short, the bootstrapper uses third-party librarys to hook the windows dynamic loader and to search in the by CSS provided .pdb for symbol references and returns them back to the dynamic loader.
So the dynamic loader is able to link the functions of the game to your custom build c++ mod.
We wont get into detail how it works in this documentation, just accept it as pure magic.

=== Satisfactory Mod Loader [.title-ref]#(aka. SML)#

Satisfactory Mod Loader (SML) allows Satisfactory to load additional
content and is essential in making most mods work.
It also provides a framework for functionally many mods need but are not provided by CSS or UE4.

Things the Mod Loader does:

* Starts the ModInit of pak mods
* Unpacks and mounts .zip packaged mods
* Manages mod dependencies
* Provides a basic interface for pak mods to interact with some native code
* Implements a Hooking system for C++ mods

If you're looking to write your own mods, we suggest you start with
making pak mods first. Learn more in our xref:beginners_guide/index.adoc[Beginners Guide].

== Installing Mods

For installing mods as end user we highly reccomend using the <<Satisfactory Mod Launcher>>.

But if you don't want to use the Launcher or you are a mod maker and want to test your mod, this is the place for you.

=== Installing Bootstrapper

Visit https://ficsit.app/bootstrap-versions[SMR/bootstrap-versions] to find the bootstrapper version you want to use and download it.

After that you just need to copy the `xinput3_1.dll` to `<game root>/FactoryGame/Binaries/Win64/`

=== Installing SML

Now that you have installed bootstrapper you need to download
a version of SML compatible with that bootstrapper version and with your game from https://ficsit.app/sml-versions[SMR].

After you have downloaded it, you need to place the file into `<game root>/loaders`.

[TIP]
====
If the folder doesn't exist, just create it or start the game with the installed bootstrapper version once.
====

=== Installing Your Mod of Choice

Ok, back to the mod itself.
On https://ficsit.app/[SMR] you just navigate to your desired mod's page, click on
`versions` in the upper right left corner and then click `+download+` on your desired version.
Usually this will be the top version in the list.

[WARNING]
====
Always check to make sure that the `SML Version` column for the version
you choose matches the version of SML you have installed. You can
attempt to install the mod with mismatched versions, but most of the
time, it won't work.
====

Now just copy the downloaded .zip file into `<game root>/mods`.

[TIP]
====
If the folder doesn't exist, just create it or start the game with bootstrapper and SML installed once.
====

=== Installing "Raw" or WIP mods

If you dont have a .zip of the mod and the proper data.json file you still can use them.

Just place the .pak, .dll and .pdb files if you need them into the mods folder and start the game with the SML config setting `developmentMode` enabled.

[WARNING]
====
SML wont be able to handle dependencies!

That means if your mod has other mods as dependencies, we can't be sure it will be loaded after the dependencies.
But you can try to name your files so its name comes after the name of the depencies if the mod list is sorted after names.
====

[TIP]
====
If you need to know how to enable `developmentMode`,
please refer to the xref:SMLConfiguration.adoc[SML Configuration Page].
====