= Satisfactory Modding Documentation

== Basics

Welcome to the Satisfactory Modding Documentation site! 

Here you can find lots of information regarding modding https://www.satisfactorygame.com/[Satisfactory], the factory-building sim by https://www.coffeestainstudios.com/games/[Coffee Stain Studios]. Modding for Satisfactory is more established than you might think given how long the game has been out. There are already https://ficsit.app/[numerous mods] released, and there are multiple methods by which you can develop new mods yourself. 

In this page, we will provide some surface level information for both mod users and developers.

[TIP]
====
If you want to take part in this great community, we recommend you
join our https://discord.gg/xkVJ73E[Discord Server] or the
https://forums.ficsit.app/[Ficsit.app Forums].
====

== For Users

If you'd like to get started using mods, this section is for you.

=== Satisfactory Mod Repository [.title-ref]#(aka. SMR aka. ficsit.app aka. FICSIT Augmentation Database)#

The Satisfactory Mod Repository (SMR) is the most extensive collection of mods made for Satisfactory. It’s easy to upload a mod of your own or write a guide for other users. Uploaded content is tested for malware and such before it is approved for download. Visit https://ficsit.app/[ficsit.app] to learn more.

=== Satisfactory Mod Manager [.title-ref]#(aka. SMM)#

The Satisfactory Mod Manager allows the end user to easily install mods, their dependencies and the mod loader.
It connects to https://ficsit.app/[SMR] allowing for a quick and easy installation process.

Check it out on https://github.com/satisfactorymodding/SatisfactoryModLauncher/releases[GitHub]!

For installing mods as end user we highly recommend using Satisfactory Mod Manager, as it makes using mods that much easier. However, if you _really_ don't want to use the launcher, directions for manual installation can be found xref:ManualInstallDirections.adoc[here].

[TIP]
====
We highly recommend you to use the launcher for installing mods, as it simplifies the process significantly.
====

== For Developers

If you'd like to write a mod of your own, this section is for you.

The Satisfactory Mod Manager offers a convenient developer mode that automatically installs SML. To enable it, change your selected profile to `development`.

If you're looking to write your own mods, we suggest you start with
making pak mods first rather than C++ mods. Learn more in our xref:Development/BeginnersGuide/index.adoc[Beginners Guide].

If you're looking to make models, it's best to learn how to put a mod together first.
Once you've completed the `Buildable` step in `Beginners Guide`, then check out our xref:Development/Modeling/index.adoc[Modeling Guide].

=== Installing Your "Raw" or WIP Mods

If you don't have a packaged mod already, create one with Alpakit.

If you have a packaged mod (.zip archived mod),
then you simply unpack the .zip into the `<SF install dir>/FactoryGame/Mods/<ModName>`.
Make sure that the `.uplugin` file is contained _directly_ within the `<ModName>` folder.

== Modding Technologies

If you'd like to learn more about how modding works internally, this is the section for you.

=== Satisfactory Mod Loader [.title-ref]#(aka. SML)#

Satisfactory Mod Loader (SML) provides a framework that makes it easier for mods to be able 
to load into systems provided by the game, and to interact with each other.
It also provides many helper features to assist in mod development.

=== Alpakit

The Alpakit is an Unreal Engine Plugin allowing you to easily cook and package your
mod for deployment and distribution.
It is also able to directly install it into your game installation for you.
