= SML Chat Commands

To use SML chat commands, type them into the chat within Satisfactory prefixed by a `/`.

For example, to run the 'help' command, you'd enter `/help` into chat.

Note that only the player who runs the command will see the command output.

== Standard Commands

This list may not be up to date; we suggest you check currently loaded commands via `/help`.

[cols="1,4a"]
|===
|Command |Description

|info
|Prints information about the SML version. Also lists all currently loaded mods.

|help
|Lists all available commands and gives a short description of their function.

|list
|Provides a list of currently connected players.
|===

== Development Mode Only commands

To enable these commands, you must have the `developmentMode` setting enabled in the xref:SMLConfiguration.adoc[SML config file]. This list may not be up to date, and commands listed here may not function as expected.

[cols="1,4a"]
|===
|Command |Description

|research_unlock
|

|research_load
|

|research_test
|
|===

