= SML Configuration

Through SML's configuration file system, it's easy for mod developers to create config files for their mods, and easy for users to change mod settings.

== Config Folder

The config files for all mods (and SML itself) reside in the same configuration file folder.

The folder is located under `<game root>/FactoryGame/Configs`.

== Config File

SML's configuration system uses json format.

All config files are located in the aforementioned <<Config Folder>> and share the same naming scheme, `<ModID>.cfg`. The config file for SML is called `SML.cfg`.

If you don't see a mod's config file listed here, it's most likely because the mod doesn't have a config file.

== SML configuration options

SML itself also provides a couple of configuration settings, allowing you to control its behavior.

[cols="1,1,1,4a"]
|===
|Name |Type |Default |Description

|enableCheatConsoleCommands
|bool
|false
|Enables all available SML console cheat commands, a list of which can be found xref:SMLChatCommands.adoc#_console_cheat_commands[here].

|developmentMode
|bool
|false
|Leave this at false, otherwise the game will load slower to no benefit (as a user).
It is necessary for part of SML development.

|consoleWindow
|bool
|false
|Toggles whether or not the external SML console window is visible.

|disabledChatCommands
|string array
|[ ]
|Allows you to disable certain chat commands by simply putting the command into the string array.
In Multiplayer, if the host lists commands here, they will also be disabled for clients.

|===
