= SML Configuration

SML's configuration file system makes it easy for mod developers to create config files for their mods
and easy for users to change mod settings.

== Config Folder

The config files for all mods (and SML itself) reside in the same configuration file folder.

The folder is located under `<game install directory>/FactoryGame/Configs`.

You can find your game install directory via the steps
xref:faq.adoc#_where_are_my_game_files_located[described in the FAQ].

== Config File

SML's configuration system uses json format.

All config files are located in the aforementioned <<Config Folder>> and share the same naming scheme, `<ModID>.cfg`. The config file for SML is called `SML.cfg`.

If you don't see a mod's config file listed here, it's most likely because the mod doesn't have a config file.

== SML configuration options

SML itself also provides a couple of configuration settings allowing you to control its behavior.

[cols="1,1,1,4a"]
|===
|Name |Type |Default |Description

|enableFunchookLogging
|bool
|false
|Enables additional logging functionality to assist with troubleshooting a
https://github.com/satisfactorymodding/SatisfactoryModLoader/issues/131[rare crash].

|disabledChatCommands
|string array
|[ ]
|Allows you to disable certain chat commands by simply putting the command into the string array.
In Multiplayer, if the host lists commands here, they will also be disabled for clients.

|===
