= Uploading your Mod to Satisfactory Mod Repository (ficsit.app)

Once you've made your amazing mod, the https://ficsit.app/[Satisfactory Mod Repository]
is the best place to upload it if you want others to find and use your mod.
Mods uploaded to SMR will automatically work with the
xref:index.adoc#_satisfactory_mod_manager_aka_smm[Mod Manager].
All mods available to SMR are checked for potential security concerns,
so having your mod on SMR means users can trust that it is safe and secure.

The process of uploading your mod is fairly straightforward.

== Create an Account on SMR

If you haven't already created an account,
you can do so by clicking 'Sign In' in the top right corner of the https://ficsit.app/[SMR homepage],
then selecting to sign in with an existing GitHub, Google, or Facebook account.

You can change your profile photo and display name on your Settings screen,
which can be accessed from your user icon in the top right corner.

== Creating your Mod Page

Before you can upload a version of your mod for users to download,
you'll first have to create a mod page.

On the 'Mods' sidebar tab of SMR, click `New Mod` in the top left corner to get started.

=== Information About your Mod

Next, add some information about your mod.

* The 'name' is the title that will appear in the mod list and browser.
* The 'short description' is the summary text that will show up below the mod icon.
* The 'full description' supports Markdown formatting (help on the https://ficsit.app/help[SMR help page])
	and is shown when the user clicks to view your mod from the all mods list.
	Consider including the following information in here:
	** A summary of what your mod adds to the game
	** Screenshots or videos of your mod in action
	** How to get started with your mod (unlock via hub milestone? features turned on by default?)
	** A means of contacting you (preferably your Discord user tag, so staff and users can identify you on the modding Discord)
	** A means of reporting bugs, such as a GitHub issues page or contact info
	** Crediting people who helped you along the way (ex. icon attribution, coding help)

If you're not sure what to write yet,
don't worry, you can come back and edit these fields later.

=== Your Mod Reference

One of the most important fields on this screen is the 'Mod Reference' field.
Explained in more detail on the
xref:Development/BeginnersGuide/index.adoc#_mod_reference[Mod Reference section of the Getting Started guide],
your mod reference is your mod's unique name.
As a reminder, your mod's plugin folder and C++ source folder (if using {cpp}) must have the same name as your mod reference.
Your mod reference cannot contain special characters or spaces.

[WARNING]
====
**You can't change your mod reference after you have added your mod to SMR!**

So make sure it is correct! At least five times!
And read up on the xref:Development/BeginnersGuide/index.adoc#_mod_reference[Mod Reference section]
again to make sure you understand what other parts of your mod need to use this same value.
====

=== Icon and Source Link

Next, you can upload an image to use as the display image for your mod.
Alternatively, you can leave this blank, and it will default to the Satisfactory Modding gear logo.

You can also provide a link to your source code, if it is hosted on a site like GitHub or similar.
We strongly encourage you to release your source code,
as it allows others to learn from your work
and helps other developers debug mod compatibility.

You can edit both of these fields later.

=== Hidden Mods

You also have the option to mark your mod as Hidden upon creation.
You can go back and edit this later.

If your mod is Hidden, it will not appear in the main mods list,
nor when browsing in SMM,
nor when searching the site.
However, other users can still find it by looking at your profile page,
and you can send people the link directly.

In addition, updates to Hidden mods will not cause messages to be sent in the `#mod-updates` channel of the modding Discord.

=== Submit your Mod Page

Once you click Submit, a page for your mod will be created.

Note that the page for your mod contains your mod's mod reference as part of the URL.
For example, the page for a mod with reference `AreaActions` would be `https://ficsit.app/mod/AreaActions`.

You still need to upload a version for your mod to be usable by players.
Until then, your mod will be marked as 'Outdated' since there are no compatible versions.
This version submission process will be covered in the following sections.

== Export your Plugin

Before you can upload a version,
there are a few fields you need to edit in your mod's uplugin file,
after which Alpakit will bundle your mod for you.

These are covered in detail on the
xref:Development/BeginnersGuide/ReleaseMod.adoc[Releasing Your Mod page].

== Uploading a Version

Once you have finished formatting your `.uplugin`,
make sure you have re-packaged your mod to include the changes with Alpakit.

Navigate to the mod page for your mod,
then select 'New Version' in the top right corner.
This will take you to a page where you can upload a version file,
as well as provide some additional info about the version.

Put "Alpha", "Beta", "Release", etc. in the stability field
so that users know how far along in development you consider this version of your mod to be.

Select the output zip from the link:#_export_your_plugin[Export your Plugin section]
with the picker the `File` field.
It will be called `YourModReference.zip`
and will be larger than all of the other zips in the folder.
This larger zip contains the zips for each target platform combined as one file ready for upload.

Finally, write up a list of all of the things you changed or added in this version for the `Changelog` field.
We also strongly suggest you copy this information into an 'update history' section of your mod's description on the main mod page.

[TIP]
====
If you decided to mark your mod as Hidden earlier,
remember to make it visible again before uploading your first version!

Otherwise, no notification will be sent on the Discord about your mod's release,
and nobody will be able (easily) to find your mod on the site.
====

You should be all set now - once you press `Create`, the upload process will begin,
and your mod will be ready for use once it completes.

[TIP]
====
Make sure to read the https://ficsit.app/content-policy[Content Policy] before uploading!
====

If any errors occur during the upload, they will be displayed on this screen.
The xref:Development/BeginnersGuide/ReleaseMod.adoc#_smr_uplugin_validator[uplugin validator] may be of use.
Consider asking for help on the Discord if you're not sure how to resolve them.

== Awaiting Approval

If you've uploaded a blueprint only mod, you're all set, and your mod is ready for download and use!
Regardless, we still suggest you read the below.

If you've uploaded a C++ mod, you'll have to wait for it to be approved by the automated approval process before users can download it.
The approval process is generally quite quick, about 1 to 3 minutes,
and exists to make sure that users aren't uploading content that violates SMR's terms and conditions or harms players' computers.

In the meantime, we strongly suggest you take a look at your mod description and consider adding additional information to it.
More on that below.

== Refine your Mod Page

The mod description is what most players will see when deciding whether or not they want to use your mod,
so keep it organized, and try to leave a good first impression!
One could say that you should try to make viewing your mod page a 'Satisfactory' experience, so to speak.

We suggest taking the following steps to encourage users to try out your mod:

- Check your grammar and spelling! Consider asking someone else to proofread your description.
	It's an easy thing to do, and having correct grammar makes you appear more professional.

- Pictures! Take some screenshots of what your mod can do, and what its buildings or features look like in game.
	Again, the long description supports Markdown formatting, which you can get help with using on the https://ficsit.app/help[help page].

- List where you can be reached for help, issue reporting, leaving suggestions, etc.
	Where do you want users to report issues to you with the mod?
	Via Discord, your mod's Github page, or somewhere else?
	Consider putting your Discord tag in your mod description so people can contact you on the community Discord,
	and consider changing your nickname on the server to include your mod name.

- Explain concepts or features of your mod that may be unclear to the user.
	Unless you write documentation or a https://ficsit.app/guides[guide] for how to use your mod,
	players might have some trouble figuring out how to use all of the amazing new content in your mod.

- List the features of your mod, and how to unlock them for use in-game.
	Consider listing what tiers the content is unlocked at.

- Credit other users that contributed ideas, models, etc. by name and/or by link.

== Uploading an Update

When you upload a new version of your mod,
make sure to change the `Version`, `VersionName`, and `SemVersion` fields
in your `<mod reference>.uplugin`.
You should also change the version specified in the mod's dependency on SML to the latest release of SML.
You can find the latest SML version release number https://ficsit.app/sml-versions[here].

These edits can be performed in the editor via the Alpakit helper
or by directly editing the `.uplugin` file in a text editor.
