= Chainsaw and Foliage

[NOTE]
====
This page is a work in progress.
====

In Satisfactory, the location of foliage is stored
as part of the game map file that is shared across all saves.
Imagine how large your save files would be if every save contained
the location of every single plant in the map!

Instead, Satisfactory saves the removal of plants in a certain radius.
The Chainsaw (and Nobelisk, and hand picking) creates
removal markers which are stored in the save file
to tell the game a plant has been removed.

If you wanted, you could use a save editor such as
https://github.com/Goz3rr/SatisfactorySaveEditor/[SatisfactorySaveEditor]
to remove all of these markers, restoring foliage to its original state.

== Make Things Chainsawable

See
https://discord.com/channels/555424930502541343/555515791592652823/779248979816218635[this message chain on the Discord]
for how to make custom foliage interact with the chainsaw.

== Make a Chainsaw

You should extend the base chainsaw when creating your own for simplicity.

The property of a chainsaw that controls the radius of
plant collection is `mCollateralPickupRadius`.

If you want something else to destory foliage,
it will need to create the foliage removal markers
that existing methods use.