= Inventories and Items

This page doesn't just describe the inventory itself,
but also everything else that is used by it.

== Item Descriptor [.title-ref]#(`UFGItemDescriptor`)#

The native `AFGItemDescriptor` class, who would have thought, 
contains properties of Item-like game concepts.
Notably, this is the base class for things like UFGBuildDescriptor (buildings)
and UFGFactoryCustomizationDescriptor (Customizer patterns),
which are not 'items' in the usual sense,
and do not make use of all available UFGItemDescriptor properties.

== Item [.title-ref]#(`FInventoryItem`)#

This structure contains information about an item (class pointer to a item descriptor) and its connected item state (any kind of actor).

== ItemAmount [.title-ref]#(`FItemAmount`)#

This struct connects just an item descriptor and a count of items, without a state.
That means this structure is not used to hold information the representation of an item in-game.
Instead, this is used, for example, in a recipe to define ingredients and products: how many of which type of items you need to supply, to get how many of which type of items as output.

== ItemStack [.title-ref]#(`FItemStack`)#

This is the brother of ItemAmount but this time it holds an Item and a count.
That means, this time, it is actually used to hold information about item and its count in-game.
e.g. how many items of what kind are in one player inventory slot?

== FGInventoryComponent [.title-ref]#(`UFGInventoryComponent`)#

This is a `USceneComponent` used to attach a inventory, able to hold multiple ItemStacks at the same time, to a actor. This is not only used for the player, it's nearly always used where you know there are items inside.
That means you can think of them like a container full of items.
