= Modding Without Satisfactory Mod Loader

[NOTE]
====
This page is still a work in progress.

If you have any feedback, please let us know in the Discord.
====

== History

Back in https://satisfactory.wiki.gg/wiki/Patch_0.3.8.9[Update 3],
Coffee Stain switched Satisfactory to being built in the Modular Build mode.
This meant that mods no longer technically needed SML to be "loaded",
so SML switched over to serving as a utility library and coordinator.

Up until the release of SML 3.8, we still required all mods uploaded to Ficsit.app to depend on SML
because it acted as a way to check which game and engine versions a mod was compatible with.

== Are You Really Sure You Want to Do This?

Benefits of still depending on SML

Consider the following SML features that you'll be losing by not depending on it:

- Significant wheel reinvention required for blueprint mods (C++ mods can use StartupModule)
- Mod dependency version checking at launch
- Client-server version consistency checking when playing in multiplayer
- Other mods being able to detect your mod's presence
- Mod Content Registry access

Also, consider that nearly every player will still have SML installed anyways so they can play with other mods.
It's already possible to run SML on just the client 


Refine the mircea paragraph:

pak-only mods need SML to act as an entrypoint to their blueprint code (or some other mod that checks for that content), while c++ has StartupModule, so it can work without any dependency. And with dedi support, client or server only mods that don't need SML may become a thing (though there's still that issue with having SML on just one side). But we still recommend listing SML as a dependency, as it checks for mod dependencies at runtime (including the game version), and client-server version consistency (when the mod is not one sided).
(This needs some rephrasing)

== Systems You Will Have to Care About

TODO

Alpakit game version dependency field

