= Schematics

Schematics are Coffee Stain Studios' answer to a research system.
Schematics hold information about requirements, visuals, and rewards of research milestones.

Everything that is technical progress ingame is a schematic.
From the analyzing stuff in the M.A.M, to the HUB Upgrades, to a AWESOME Shop purchases, to the Tier stages of the Space Elevator, everything is a Schematic.

The requirements (item costs, prerequisites, time) of a schematic are directly set in the schematic, but the rewards are defined by so called "unlocks".
These unlocks can be anything from new recipes over new buildings to now inventory slots.

If you want to implement custom milestones or M.A.M researches in your mod, you'll need to make schematics.

== FGUnlock (`UFGUnlock`)
This is the class describing a reward you get when a schematic gets unlocked.
It can be anything from recipes or other schematics to inventory slots.

CSS already provides a couple of these as native classes but also Blueprint wrapper classes
allowing for a even easier and better usage in the schematics
so you don't need to create many custom unlocks derived from the CSS ones to set the default values.
Instead the BP wrappers allow you to define these default values in the schematic directly.

Below is a list of available unlocks you can use and their BP wrappers:

[cols="1,4a"]
|===
|BP Wrapper |Description of Function

|UnlockArmEquipmentSlot
|Gives the player additional arm equipment slots. Having more than 6 causes the inventory screen to look weird, but they still work.

|UnlockBuildEfficency
|

|UnlockBuildOverclock
|

|UnlockGiveItem
|

|UnlockInventorySlot
|Gives the player additional inventory slots. 

|UnlockMap
|Allows the player to access the ingame minimap screen. The base game already does this with the map research.

|UnlockRecipe
|Unlocks crafting or building recipes for use by the player.

|UnlockScannableResource
|Adds a resource to the resource scanner.

|UnlockSchematic
|Unlocks another FGSchematic when this one is completed.

|UnlockSubsystem
|
|===

== FGSchematic (`UFGSchematic`)

The FGSchematic class holds the general information about a research milestone.
These research milestones can be anything from a M.A.M research node, to a HUB Upgrade, to a Space Elevator Tier.

* {blank}
+
M Type::
  The type of the schematic, which determines if it's part of the
  tutorial system, M.A.M, AWESOME Shop, a Milestone, etc.
* {blank}
+
M Display Name::
  The in-game name of our schematic exactly as it is displayed to the player.
* {blank}
+
M Schematic Category::
  Defines the category in which this schematic gets grouped into.
* {blank}
+
M Sub Category::
  Defines in which sub groups the schematic should get categorized into.
* {blank}
+
M Tech Tier::
  Determines in which Tier the schematic will appear under in the HUB.
* {blank}
+
M Time to Complete::
  This defines the time how long the space ship will be away after purchase of the schematic, or how long it takes the M.A.M to process the research node.
* {blank}
M Schematic Icon::
  The icon displayed on the schematic in the HUB or M.A.M.
* {blank}
+
M Depends on Schematic::
  Setting this option will require the selected schematic to be
  activated first before this one can be activated. This is used in the M.A.M to create prerequisites.
* {blank}
+
M Additional Schematic Dependencies::
  Similar to `M Depends on Schematic`.
  Additional schematics to be dependent on can be listed here.
* {blank}
+
M Cost::
  A list of item amounts which are required to purchase the schematic.
* {blank}
+
M Unlocks::
  This array contains the rewards the player will get when unlocking this schematic.
  It is a array of xref::/Development/Satisfactory/Schematic.adoc#_fgunlock_ufgunlock[FGUnlock]s.
* {blank}
+
M Include In Builds::
  This defines in which builds the schematic should be able to get loaded/cooked.
  Presumably, this is what Coffee Stain uses to keep their developer milestones made for testing
  from being shipped with the main game.
  Its recommended to set this to `Shipping`, otherwise players probably won't be able to use your mod.
