= Create a Simple Mod

Now that you have learned the core concepts of Satisfactory modding, you can get started on creating your first mod.

== Overview

To get started, this tutorial will walk you through creating a simple
mod that adds the following:

* {blank}
+
The required core functions that register the mod with the game and
allow its content to be added
* {blank}
+
A custom recipe to make 1 Wood from 42 Leaves
* {blank}
+
A HUB Milestone to purchase in order to unlock our custom recipe
* {blank}
+
A new item to produce - a flatscreen TV called a 'Doc Item'
* {blank}
+
A new buildable object that can be painted with the paint gun
* {blank}
+
A basic machine that consumes power and counts the number and
types of items that pass through it 

[TIP]
====
Knowledge about 3D modeling is very helpful if you want to add new items, buildings, enemies, etc. to the game.
If you have an idea for such a mod but aren't experienced with modeling,
consider posting it in the `#ideas-discussion` channel on the
https://discord.gg/xkVJ73E[Discord server].
You may find an artist willing to work with you on a project.
You could also learn how to model in a program like Blender, Meshmixer, Maya, etc.
====

== Next Steps

Get started with the xref:Development/BeginnersGuide/SimpleMod/gameworldmodule.adoc[Plugin Setup and Game World Module], the entry point for your mod.
