= Development

If you'd like to make your own mod, this section of the docs is for you!

Here you can find information regarding making mods and getting your development environment up and running.
Check out the subcategories on the left to get started.

If you're just looking to play Satisfactory with mods, check out how to install mods xref:index.adoc#_for_users[here] instead.

== Resources

Below is a list of some good resources about making mods for SF, UE4, C++ and 3D Modeling. Please contact us if you know of other resources that should be added to this list.

- https://www.youtube.com/channel/UCOVfF7PfLbRdVEm0hONTrNQ[Mathew Wadstein] 
+
A good YouTube Channel showing a more in-depth look at features of UE4 (BP only).
- https://www.youtube.com/channel/UCz-eYJAUgSE-mqzKtit7m9g[Virtus Learning Hub]
+
A "general" tutorial series channel for UE game development (also covers some C++)
- https://www.youtube.com/channel/UCYoV5-xnSC2BGseQ_nHWufw[Miles Nocte's Channel]
+
A series of SF modding tutorials made by MilesNocte, a member of our community.
**As of SML 3.0.0, these tutorials are partially out of date, but many of the concepts will still carry over.**
- http://academy.unrealengine.com/[Unreal Engine Academy]
+
A neat learning platform made by Epic Games for learning Unreal Engine.
