= Multiplayer Testing

== Instructions

[NOTE]
====
This page is a work in progress. It currently just consists of a modified version of
https://discord.com/channels/555424930502541343/689188183048585244/782335816629223475[this message]
in the Discord.
====

Run 2 games of Satisfactory for multiplayer testing in a few easy steps!

1. Create a new Powershell script with the contents of the below 
code block and edit the first line to the game install folder.
Note: You can edit the 2nd and 3rd line for a custom name

2. Run the script in Powershell (by right clicking it and hit "run by powershell")
and wait for both copies of the game to load.

3. Open up your save file in either copy of the game. 

4. Once you've loaded in, go to the second game instance and open the console by pressing
Ctrl+Shift+L, then the ` (backtick/grave) key.
(NOTE: this seems to work only with the Windows UK keyboard Layout,
not a physical one, but in Windows set it to UK keyboard layout).
Then type in `open 127.0.0.1` and hit enter.
The second instance will now connect to the game hosted by the first instance.

== Powershell Launch Script

[source,ps1]
----
$GameDir = "C:\Program Files\Epic Games\SatisfactoryEarlyAccess"
$Username1 = "Player1"
$Username2 = "Player2"

$Args1 = "-EpicPortal", "-NoSteamClient", "-NoMultiplayer", '-Username="'+$Username1+'"'
$Args2 = "-EpicPortal", "-NoSteamClient", "-NoMultiplayer", '-Username="'+$Username2+'"'

function BGProcess(){
    Start-Process -NoNewWindow @args
}

BGProcess "$($GameDir)\FactoryGame\Binaries\Win64\FactoryGame-Win64-Shipping.exe" $Args1

sleep -m 5000

BGProcess "$($GameDir)\FactoryGame\Binaries\Win64\FactoryGame-Win64-Shipping.exe" $Args2
----