= Open Source Examples

====
TODO SCS hooks -> Actor Mixins, Blueprint Hooks
====

It's impossible for this documentation to cover every aspect of making Satisfactory mods.
However, there are quite a few open-source mods you can download and check out the code of
to learn how they accomplish certain behaviors or features.

This page contains a community-maintained list of open-source mods,
as well as what Satisfactory and SML features they make use of,
to help guide your learning.

Open source mods typically provide their source code in the "Source" section of the infobox on the mod repository.

You can set up these mods in your editor by following the
xref:Development/BeginnersGuide/ImportingAnotherMod.adoc[Importing Other Mods to your Project] guide.

Would you like to make your mod open source so others can learn from it as well?
Get started by following the xref:Development/BeginnersGuide/CreateGitRepo.adoc[Creating a Mod Git Repo] guide.

[TIP]
====
This page is a continual work in progress.
Are you aware of an open-source mod to list here?
Add it via the "Edit This Page" button in the top right corner and open a Pull Request to bring in your changes.
====

== MAM Enhancer

Modifies the base game MAM, HUB, and AWESOME Shop UI to provide additional information to the player and improve the user experience.

_Source Code_: Linked on the https://ficsit.app/mod/MAMTips[Mod Page]

_Mod Type_: Hybrid Blueprint/{cpp}

_Notable Techniques Used:_

* Widget Injection
** Modify the base game's interface to hide, change, and add new elements
* In-game tutorial
** An icon with a tooltip that encourages the player to see how to use the mod after installing it,
   then dismisses itself for later

_Notable Satisfactory Features Used:_

* xref:Development/Satisfactory/ShoppingList.adoc[To-Do/Shopping List]
** Adds schematics to the player's Shopping List list

_Notable Mod Loader Features Used:_

* Mod Configuration
** Live preview of user's selected config options
** Binding events to the change of config options
** Programatically modifying config values and saving the changes
* Bind on BP Function
* Widget Blueprint Hooks
* Session Settings

== Free Samples

Whenever you unlock a technology that grants you a recipe, receive a configurable amount of 'free samples' of that recipe. For equipment and component crafting recipes, this is the output product. For buildings, this is the ingredients for the building. Every player in multiplayer gets a copy of the free sample items.

_Source Code_: Linked on the https://ficsit.app/mod/FreeSamples[Mod Page]

_Mod Type_: Hybrid Blueprint/{cpp}

_Notable Techniques Used:_

* Programatically giving items to players
* Compatibility with runtime-generated assets
** Works properly with Recipes and Schematics that might not yet exist when the player loads the world
* Per-player data storage (multiplayer compatibility)
* Save/loading of soft class and soft object fields
* Hybrid Blueprint/{cpp} subsystems
** Subsystems' final implementations are in Blueprint,
   but they are backed by custom {cpp} parent classes to allow {cpp} mods to reference the data fields.
* Zero-dependency cross mod interaction
** Mod is coded to inspect other mod's assets for fields with a certain name,
   and then change behavior based on those fields values.
   Enables cross-mod interaction without either mod needing the other's source code.

_Notable Satisfactory Features Used:_

* None

_Notable Mod Loader Features Used:_

* Mod Subsystems
** Server-side only subsystems since adding inventory items requires authority
* Simple Construction Script (SCS) Hooks
** Used to implement per-player data storage
* Chat Commands
* Mod Configuration
** Custom config widget to make entering data easier
** Tracking if the user has modified the config from the defaults
   to know if future mod updates should automatically overwrite them with updated default data
** Programatically modifying config values and saving the changes
* xref:Development/ModLoader/ContentTagRegistry.adoc[Content Tags]
** Tags can be used to specify items/recipes/schematics to skip from sample consideration without mod source dependencies.

== Screw It

Meme mod, changes most things to be named and/or look like Screws.

_Source Code_: Linked on the https://ficsit.app/mod/ScrewIt[Mod Page]

_Mod Type_: Hybrid Blueprint/{cpp}

_Notable Techniques Used:_

* Using the Asset Registry to quickly discover subclasses (both vanilla and modded)
* Asynchronous asset loading to avoid stalling the game while waiting for disk I/O
* Class Default Object (CDO) modification
** CDO edits in bulk (on the aforementioned loaded classes), implemented in {cpp}
* Hybrid Blueprint/{cpp} game instance module
** Root instance's final implementations is in Blueprint,
   but it is backed by a custom {cpp} parent class to be
   able to easily reference Blueprint-only assets

_Notable Satisfactory Features Used:_

* None

_Notable Mod Loader Features Used:_

* Access Transformers, to be able to change otherwise inaccessible member variables.

[id="CableChoicesPlus"]
== Cable Choices {plus}

Adds a number of new variants of existing buildings (power cables and poles) as well as some buildings with custom functionality.

_Source Code_: Linked on the https://ficsit.app/mod/AB_CableMod[Mod Page]

_Mod Type_: Hybrid Blueprint/{cpp}

_Notable Techniques Used:_

* Custom models that follow the Satisfactory style
* Building icons generated with xref:CommunityResources/IconGenerator.adoc#_beavers_icon_generator[Beaver's Icon Generator]
* GitHub repository that contains additional files (the source models) in a clean structure
* Custom UI/UX
** Settings panel to reorganize build menu
* Base game content modifications
** Adds an additional recipe for the existing FICSMAS powerline lights
** Injects some unlocks into existing milestones

_Notable Satisfactory Features Used:_

* Customizer
** Skins (Power Cables)
** Building Materials (Power Cables)
* xref:Development/Satisfactory/BuildableHolograms.adoc[Buildable Holograms] with custom logic
** Snapping a power connector to spline based rail tracks
** Snapping power towers to each other with simple rules
** Behaviors for well aligned wall/foundation snapping (Delay Switch)
* Building interaction UIs
** Completely new UIs with source (Delay Switch)
** Retrofitted vanilla UIs to function elsewhere (Rail Power Box)

_Notable Mod Loader Features Used:_

* Mod Configuration
** Settings panel to reorganize build menu

[id="FluidExtras"]
== Fluid Extras

Adds a number of new variants of existing fluid junctions as well as several buildings with custom functionality.

_Source Code_: Linked on the https://ficsit.app/mod/AB_FluidExtras[Mod Page]

_Mod Type_: Hybrid Blueprint/{cpp}

_Notable Techniques Used:_

* Custom models that follow the Satisfactory style
* Building icons generated with xref:CommunityResources/IconGenerator.adoc#_beavers_icon_generator[Beaver's Icon Generator]
* GitHub repository that contains additional files (the source models) in a clean structure
* Custom Building Logic
** Custom fluid building that deletes input and animates based upon it (Exhaust)
** Custom building that detects input and selects recipes based on it (AI Packager)
* Custom UI/UX
** Settings panel to reorganize build menu

_Notable Satisfactory Features Used:_

* xref:Development/Satisfactory/BuildableHolograms.adoc[Buildable Holograms] with custom logic
** New and expanded behaviors for Junctions (in development)
** Modified Water Extractor that can snap to foundations (in development)
** Building that can snap to pipes and walls (Exhaust: Unreleased but pushed)
** Complex placement tolerance rules (Exhaust: in development)
* Building interaction UIs
** Completely new UIs with source (Exhaust)

_Notable Mod Loader Features Used:_

* Mod Configuration
** Settings panel to reorganize build menu

[id="BeaversFicsmasBooster"]
== Beaver's Ficsmas Booster

Adds a number of new customizer building material and complex decorative parts. Uses seasonal toggles and several new from scratch materials.

_Source Code_: Linked on the https://ficsit.app/mod/AB_XMASBooster[Mod Page]

_Mod Type_: Hybrid Blueprint/{cpp}

_Notable Techniques Used:_

* Seasonal development each year
* Custom models that follow the Satisfactory style
* Building icons generated with xref:CommunityResources/IconGenerator.adoc#_beavers_icon_generator[Beaver's Icon Generator]
* GitHub repository that contains additional files (the source models) in a clean structure
* New Content
** Complex shader/mesh combo to create seamless gingerbread pieces when built
** Freeform spline buildings unlike other decorative parts (Icing)

_Notable Satisfactory Features Used:_

* Seasonal Events
** Many schematics and recipes are hidden behind the event check
* Customizer
** Building Materials (Gingerbread)
** Custom render material that still respects foundation decals (Gingerbread)
* xref:Development/Satisfactory/BuildableHolograms.adoc[Buildable Holograms] with custom logic
** Multi stage, Multi mode; Spline drawing hologram (Icing)

_Notable Mod Loader Features Used:_

* None

[id="BetterTrainCollision"]
== Better Train Collision

Replaces base game locomotive collision mesh.

_Source Code_: Linked on the https://ficsit.app/mod/BetterTrainCollision[Mod Page]

_Mod Type_: Pure Blueprint

_Notable Techniques Used:_

* Runtime actor modification
** Replaces locomotive collisions with custom collision mesh
** Makes sure only the base game train's mesh collisions are replaced,
   avoiding accidentally modifying other mods' trains

_Notable Satisfactory Features Used:_

* None

_Notable Mod Loader Features Used:_

* Simple Construction Script (SCS) Hooks
** Used to detect instances of locomotives and trigger the code to replace their collision mesh

[id="EarlyAndFreeBlueprintDesigner"]
== Early Free Blueprint Designer

Unlocks the Blueprint Designer Mk1-3 and Blueprint usage from the start of the game,
and makes designers cost no resources to build.

_Source Code_: Linked on the https://ficsit.app/mod/EarlyAndFreeBlueprintDesigner[Mod Page]

_Mod Type_: Pure Blueprint

_Notable Techniques Used:_

* Class Default Object (CDO) modification
** Class default object of recipes to make them free to build

_Notable Satisfactory Features Used:_

* None

_Notable Mod Loader Features Used:_

* xref:Development/ModLoader/ContentTagRegistry.adoc[Content Tags]
** Scans all recipes and all schematics for a specific tag and modifies them when present
** Enables easy extending the mod to affect other mods' blueprint designers.
   Any recipe with the relevant tag is made free and any schematic with the relevant tag is given for free.

[id="ThisSignUp"]
== This Sign Up

Adds arrows to indicate which way is up when building a sign.

_Source Code_: Linked on the https://ficsit.app/mod/ThisSignUp[Mod Page]

_Mod Type_: Pure Blueprint

_Notable Techniques Used:_

* None

_Notable Satisfactory Features Used:_

* None

_Notable Mod Loader Features Used:_

* Simple Construction Script (SCS) Hooks
** Used to spawn an additional actor component on sign placement holograms (the upwards facing arrow)
