= Upgrading from SML 3.9.x to 3.10.x

[NOTE]
====
You have found a hidden docs page!

This page is still a work in progress.

If you have any feedback, please let us know in the Discord.
====

TODO

Look for // TODO SML3.10.0 docs comments before merging

Please _read this entire page before you begin updating your mod_.
It will save you time later to have an idea going in of what to expect while updating.
After you have finished reading this page,
follow the directions on the
xref:Development/UpdatingToNewVersions.adoc[Updating your Mod]
guide to install the updated engine, starter project, and update your mod.

== New Features

This section talks about the new features that SML 3.10 brings to the table.

TODO

- BlueprintType access transformer
- EditAnywhere access transformer

== Notable Fixes

TODO

== Not Done Yet

The following features are not quite ready to use yet.

=== Advanced Game Settings values not saved

The xref:Development/ModLoader/SessionSettings.adoc[Session Settings] page
explains how you can create your own Advanced Game Settings.
However, their values are not currently saved with the save file.
Session Settings still function correctly - their values are saved.

=== Content Bundle Cooking

The optimal way to add modded content to the game world (like ore nodes, deposits, etc.)
is to use the Content Bundle system,
but Unreal currently refuses to cook content bundles unless the world is also cooked.
This is a https://github.com/satisfactorymodding/SatisfactoryModLoader/issues/155[known bug]
and will be fixed in a future SML release.

The next best way is to use sublevel spawning. Here is an example from Kyrium of how to do that:

* https://github.com/Satisfactory-KMods/KBFL/blob/d21381de3621d25f063ecfbf24b5d35533da4357/Source/KBFL/Private/Subsystems/ResourceNodes/KBFLSubLevelSpawning.cpp#L41[KBFLSubLevelSpawning]
* https://github.com/Satisfactory-KMods/KBFL/blob/d21381de3621d25f063ecfbf24b5d35533da4357/Source/KBFL/Private/Subsystems/KBFLResourceNodeSubsystem.cpp#L67[KBFLResourceNodeSubsystem]

== Required Changes

In addition to any specific-to-your-mod issues you may encounter,
the changes described below _must_ be made in order for your mod to be updated.

TODO

- There are no required changes for this SML update!

== Additional Changes

You might not be affected by these changes,
but we'd like to draw extra attention to them.

TODO 

- cpp Chat command usage FString -> FText
- Cpp Mod config desc FString -> FText