= Upgrading from SML 3.11.x to 3.12.x

[IMPORTANT]
====
SML 3.12 and 1.2 support have not been released yet!
The contents of this page will change frequently!
Keep your eyes on the `#modding-info-feed` Discord channel to be notified when updates are made.
====

SML3.12 brings support for Satisfactory 1.2.
As a major update bundled with an Unreal Engine upgrade,
most mods are expected to need recompilation with the new engine and game headers.

Please _read this entire page before you begin updating your mod_.
It will save you time later to have an idea going in of what to expect while updating.
After you have finished reading this page,
follow the directions on the
xref:Development/UpdatingToNewVersions.adoc[Updating your Mod]
guide to install the updated engine, starter project, and update your mod.

== Versioned Cooked Content

TODO move this heading?

Since Alpakit uses xref:Development/UpdatingFromSml310.adoc#_alpakit_versioned_cooked_content[Versioned Cooked Content] as of SML 3.10,
there is a chance that some blueprint-only mods packaged for SML3.10 will require no changes to function properly in Satisfactory 1.2.

Since it's not possible for an end user to predict which mods will or won't work,
we are not planning to announce this, except to careful readers of this page - hey, that's you!
It's up to mod developers and attentive community members to test mods and update their ficsit.app Compatibility Info accordingly.

As a general rule of thumb, your mod will probably NOT have survived if:

- It includes includes any {cpp} modules
- It interfaces with systems changed in Satisfactory 1.2, like vehicles
- It worked with user input, especially for controllers
- You stepped outside on a rainy day while wearing 1 sock on the wrong foot during the 1.2 experimental (that is to say, there are factors we aren't aware of yet)

To test whether your mod still works without recompiling:

1. Install your published SML3.10-dependent mod via Satisfactory Mod Manager
   or by xref:ManualInstallDirections.adoc[manually installing it].
2. As SML 3.12 is not currently released, it is not available on SMM.
   Use Alpakit to package a version of SML yourself.
   Note that SMM will replace your self-packaged copy of SML if it detects that changes are required.
3. Launch your game and test your mod accordingly
4. If your mod functions without a recompile, update its Compatibility Info on the mod page accordingly.
   No need to build and upload a new version.

== New Features

This section talks about the new features that Satisfactory 1.2 and SML 3.12 bring to the table.

=== User Config Resetting

TODO Additional details, see https://github.com/satisfactorymodding/SatisfactoryModLoader/pull/364/

Users can now reset xref:Development/ModLoader/Configuration.adoc[Mod Configuration options] to their default values directly from the config screen.
Package ExampleMod and try it out in game!

As a mod developer, you can exclude certain options from being reset ('Allow User Reset'),
check if a setting is at its default value, or trigger a reset yourself via code.
If a config section disallows reset, all options within that section are also unable to be reset.

All existing default values and user config choices have been preserved.
Although you do not technically need to change anything for your mods to get this feature,
it is worth reviewing your configuration to see if there are any values that the user should not be allowed to reset.

=== ficsit.app Controller Compatibility Tracking

TODO currently only live on ficsit.dev

ficsit.app now allows you to communicate if your mod works with controllers, such as Xbox, Playstation, or Steam controllers.
This information is presented and stored in a system similar to the existing Stable and Experimental branch compatibility.

The possible options are:

- **Untested** - (Leave your mod at this unless you have a good reason to otherwise.) No controller support information has been reported for this mod yet. Try it out and contact us on the Discord so it can be updated!
- **Unsupported** - You will need to use a mouse and keyboard to interact with elements introduced by or altered by this mod.
- **Partial** - This mod partially supports playing with a controller, but there are still some things missing. You may need to use a mouse and keyboard to interact with some elements introduced by or altered by this mod. Be sure to read the note and see an explanation!
- **Supported (Implicit)** - This mod supports playing with a controller. This is because the mod does not introduce or modify any systems that require an explicit effort to support controllers - existing controller support already covers it.
- **Supported** - This mod supports playing with a controller. The developer has made a specific effort to ensure that playing with a controller is possible and tested it themselves.

This information is currently only visible on ficsit.app, not inside of SMM.

=== ficsit.app Disclosures

TODO currently only live on ficsit.dev, and there are pending content policy edits not on dev yet

ficsit.app now offers a consistent location for mods to place their Network Activity Transparency information.
Previously, this information was expected to be somewhere inside the mod description text.
This new change helps users find the information quickly and ensures developers know they need to provide it.
Together with this field is a new one for disclosing generative AI usage.

You can read more about what information must be disclosed in the link:https://ficsit.app/content-policy[ficsit.app Content Policy].

Note that uploading additional versions of your mod is blocked until disclosure questions are answered.

This information is currently only visible on ficsit.app, not inside of SMM.

=== TODO Remaining New Features

== Not Done Yet

The following features are not quite ready to use yet.

=== Unreal Game Features

Changes in 1.2 allow Satisfactory mods to take advantage of the link:https://dev.epicgames.com/documentation/unreal-engine/game-features-and-modular-gameplay-in-unreal-engine?application_version=5.6[Unreal Game Features and Modular Gameplay] system.
Game Features are similar to SML's xref:Development/ModLoader/ModModules.adoc[Game Instance Modules].

[IMPORTANT]
====
SMM and ficsit.app do not yet support distribution of mods using the Game Feature asset structure.
We expect to be adding this functionality in the months after the 1.2 release.
====

ExampleMod has been updated to package its files using Game Features.

In the future the link:https://dev.epicgames.com/documentation/unreal-engine/world-partition---data-layers-in-unreal-engine?application_version=5.6[World Partition Data Layers] system,
with data layers loaded by Game Features, will be the intended approach for creating additions to the game map,
like new ore nodes or terrain elements, replacing the current sublevel spawning approach.

== Required Changes

In addition to any specific-to-your-mod issues you may encounter,
the changes described below _must_ be made in order for your mod to be updated.

=== Dependency Updates

The following project dependencies have updated.
Install the updated versions as you follow the xref:Development/UpdatingToNewVersions.adoc[Updating your Mod] guide.

==== Engine Update

Satisfactory 1.2 brings the game to Unreal Engine 5.6.1.
Download and set up our custom release while following the
xref:Development/UpdatingToNewVersions.adoc[Updating your Mod guide].

==== Clang Toolchain Update

This updated engine version also requires an updated clang toolchain.
Download and set up the new toolchain while following the
xref:Development/UpdatingToNewVersions.adoc[Updating your Mod guide].

==== Wwise Update

CSS has also updated to a newer version of Wwise.
The xref:Development/BeginnersGuide/dependencies.adoc#_wwise[Dependencies page Wwise instructions]
lists the new Wwise version and guides you through integrating it into your project as you follow the
xref:Development/UpdatingToNewVersions.adoc[Updating your Mod guide].

=== Generate Wwise Sound Banks

If you see the "GeneratedSoundBanks folder does not seem to be set. Would you like to open the settings window to set it?" message, use the Wwise editor to
xref:Development/BeginnersGuide/project_setup.adoc#Wwise_GenerateBanks[manually generate sound banks once],
You should not need to do this again unless you create a new Wwise project or use Wwise systems in your mod.

=== Unreal Pointer Migration

TODO

Satisfactory has switched to use Unreal `TObjectPtr<>`s instead of raw pointers (for example, `UObject*`) in their codebase
for the memory and dependency management benefits it offers.

Any {cpp} mods using raw pointers to UObjects/UStructs/UProperties
must switch to this format to avoid crashes (`It will build somewhat fine like this but not using TObjectPtr might result in GC crashes if/when we enable Incremental GC` - Arch).
In the next SML update, mods still using raw pointers will be unable to compile.
You can force this compile-time check now by adjusting the Unreal Header Tool configuration:

```ini
[UnrealHeaderTool]
; ...
; <CSS> FactoryGame has been migrated to use TObjectPtr, disallow native pointers in game code
NonEngineNativePointerMemberBehavior=Disallow
```

In most cases the swap can be a drop-in replacement,
as TObjectPtr can automatically cast to a raw pointer as needed,
but link:https://www.youtube.com/watch?v=j0zf1VOegk8[it can't automatically cast to a pointer-by-reference],
which may require additional code changes.

Unreal has provided a conversion tool that can update portions of your code automatically: link:https://dev.epicgames.com/documentation/unreal-engine/unreal-engine-5-migration-guide?lang=en-US#optionalconversiontool[Unreal Engine 5 Migration Guide: Optional Conversion Tool]

Steps to run tool? https://discord.com/channels/555424930502541343/1486398610706006117/1509348752857497650

It is unclear if this tool will work properly for mods.
Please try it and report back on the Discord.

=== TODO More Required Changes

== Additional Changes

You might not be affected by these changes,
but we'd like to draw extra attention to them.

=== Enhanced Input Mapping Context Parent Class Change

TODO

Need to use FGChildInputMappingContext if using parent context registration

Also need to be using GameFeatures for it to be auto detected otherwise need to manually register (no longer using parent approach https://discord.com/channels/555424930502541343/562722670974599227/1509904209649340558)

Do they need special register steps in gamefeaturedata? https://discord.com/channels/555424930502541343/562722670974599227/1509918327420616805

The `mParentContext` field has been moved from UFGInputMappingContext to UFGChildInputMappingContext, so the value set on existing assets will be lost. Hope you kept your old editor around so you can check it! Or maybe fmodel/contentinspector could tell you

UE right click menu on asset lets you change the parent class

https://github.com/satisfactorymodding/SatisfactoryModLoader/pull/417

=== Asset Dumping with `-nullrhi` no longer works

Dumping assets with `-nullrhi` is no longer possible, because Unreal Engine doesn't load mesh data when using that anymore, 
as a dedicated servers memory optimization. 

`-RenderOffscreen` can be used instead, which will still use the GPU to render, but without the game window.

=== ExampleLevel Lighting Update

Archengius has updated Example Level's lighting to use exactly the same settings as the base game.
If you've developed a custom map,
check out the settings and lighting actors inside ExampleLevel so you can match the base game's settings.

TODO list of places to look at specifically?

=== Console Shared Codebase

Note that Satisfactory 1.2 brings the PC and console versions of the game to the same codebase.
Although xref:faq.adoc#ConsoleSupport[it is still not possible to develop mods for consoles],
you may notice additional code and assets for console support code.

=== Custom Icon Libraries on Servers

1.2 fixes a base-game bug content registration bug,
allowing modded xref:Development/Satisfactory/IconLibrary.adoc[Icon Libraries]
to work properly on dedicated servers.
No changes to existing icon libraries are known to be required for the fix to work.

=== TODO More Additional Changes

== Complete Changelog

[NOTE]
====
This link temporarily compares to the `dev` branch since there is no 3.12 tag until release.
====

The full list containing every changed file and asset can be viewed using GitHub's Compare Changes feature:
// https://github.com/satisfactorymodding/SatisfactoryModLoader/compare/v3.11.3...v3.12.0
https://github.com/satisfactorymodding/SatisfactoryModLoader/compare/v3.11.3...dev