= Upgrading from SML 3.9.x to 3.10.x

SML3.10 

Please _read this entire page before you begin updating your mod_.
It will save you time later to have an idea going in of what to expect while updating.
After you have finished reading this page,
follow the directions on the
xref:Development/UpdatingToNewVersions.adoc[Updating your Mod]
guide to install the updated engine, starter project, and update your mod.

== New Features

This section talks about the new features that SML 3.10 brings to the table.

=== Wwise Integration

Although technically introduced in SML 3.9.1,
the first round of documentation for using the Wwise audio system is now written.

Check out the xref:Development/Satisfactory/Audio.adoc[Audio] page for more information.

=== BlueprintType Access Transformer

TODO

=== EditAnywhere Access Transformer

TODO

=== Custom Icon Libraries

The addition of the EditAnywhere Access Transformer makes implementing custom Icon Libraries very straightforward.
Icon Libraries provide images for usage on signs, map stamps, and map icons.

Check out the xref:Development/Satisfactory/IconLibrary.adoc[Icon Libraries] page for more information,
and Example Mod's `ExampleModIcons` asset for an example of a custom Icon Library.

[NOTE]
====
A base-game bug prevents custom icon libraries from working on modded dedicated servers.
This bug is expected to be resolved in the Satisfactory 1.1 update.
====

=== Recipe Linter

A new editor utility included with SMLEditor helps you check your recipes for potential problems or oversights.
It's relatively easy to expand the system to write your own checks as well.

To use the utility, select one or more assets descending from FGRecipe,
then right click on one and run
`Scripted Asset Actions` > `SMLEditor: Lint Recipes for Common Mistakes`.
Output will be displayed in the editor Output Log tab.

Read more on the xref:Development/EditorTools/SMLEditor/SMLEditor.adoc#RecipeLinter[SML Editor Utilities] page.

== Notable Fixes

TODO

== Not Done Yet

The following features are not quite ready to use yet.

=== Advanced Game Settings values not saved

The xref:Development/ModLoader/SessionSettings.adoc[Session Settings] page
explains how you can create your own Advanced Game Settings.
However, their values are not currently saved with the save file.
Session Settings still function correctly - their values are saved.

=== Content Bundle Cooking

The optimal way to add modded content to the game world (like ore nodes, deposits, etc.)
is to use the Content Bundle system,
but Unreal currently refuses to cook content bundles unless the world is also cooked.
This is a https://github.com/satisfactorymodding/SatisfactoryModLoader/issues/155[known bug]
and will be fixed in a future SML release.

The next best way is to use sublevel spawning. Here is an example from Kyrium of how to do that:

* https://github.com/Satisfactory-KMods/KBFL/blob/d21381de3621d25f063ecfbf24b5d35533da4357/Source/KBFL/Private/Subsystems/ResourceNodes/KBFLSubLevelSpawning.cpp#L41[KBFLSubLevelSpawning]
* https://github.com/Satisfactory-KMods/KBFL/blob/d21381de3621d25f063ecfbf24b5d35533da4357/Source/KBFL/Private/Subsystems/KBFLResourceNodeSubsystem.cpp#L67[KBFLResourceNodeSubsystem]

== Required Changes

In addition to any specific-to-your-mod issues you may encounter,
the changes described below _must_ be made in order for your mod to be updated.

TODO

=== Generate Wwise Sound Banks

// TODO actually required?

Changes made to enable Wwise integration in SML 3.9.1 caused the editor to crash when opening game level assets due to an edge case in the Wwise plugin code.

To avoid these editor crashes, manually 

xref:Development/Satisfactory/Audio.adoc#_generating_sound_banks[respective section].

== Additional Changes

You might not be affected by these changes,
but we'd like to draw extra attention to them.

TODO 

- cpp Chat command usage FString -> FText
- Cpp Mod config desc FString -> FText