= Upgrading from SML 3.11.x to 3.12.x

[IMPORTANT]
=====
This guide is still a work in progress and is not in a state to be followed yet.
Attempt to upgrade at your own risk, we are still working on this document.
=====

SML3.12 brings support for Satisfactory 1.2.

Mods compiled for SML3.11 are not expected to work with SML3.12 due to upgrading the Unreal 
Engine to 5.6.1 and changes to the base game headers.

Please _read this entire page before you begin updating your mod_.
It will save you time later to have an idea going in of what to expect while updating.
After you have finished reading this page,
follow the directions on the
xref:Development/UpdatingToNewVersions.adoc[Updating your Mod]
guide to install the updated engine, starter project, and update your mod.

== New Features

This section talks about the new features that SML 3.12 brings to the table.

TODO: Add new features when we have them, and add more detail to the ones we already have listed.

== Not Done Yet

The following features are not quite ready to use yet.

TODO: Are they done yet? If so, add instructions for how to use them.

=== Advanced Game Settings values not saved

The xref:Development/ModLoader/SessionSettings.adoc[Session Settings] page
explains how you can create your own Advanced Game Settings.
However, their values are not currently saved with the save file.
Session Settings still function correctly - their values are saved.

=== Content Bundle Cooking

The optimal way to add modded content to the game world (like ore nodes, deposits, etc.)
is to use the Content Bundle system,
but Unreal currently refuses to cook content bundles unless the world is also cooked.
This is a https://github.com/satisfactorymodding/SatisfactoryModLoader/issues/155[known bug]
and will be fixed in a future SML release.

The next best way is to use sublevel spawning.
ExampleMod uses sublevel spawning to spawn its example resource nodes - check the game world submodule.
Here is an example from Kyrium of how to do that in {cpp}:

* https://github.com/Satisfactory-KMods/KBFL/blob/d21381de3621d25f063ecfbf24b5d35533da4357/Source/KBFL/Private/Subsystems/ResourceNodes/KBFLSubLevelSpawning.cpp#L41[KBFLSubLevelSpawning]
* https://github.com/Satisfactory-KMods/KBFL/blob/d21381de3621d25f063ecfbf24b5d35533da4357/Source/KBFL/Private/Subsystems/KBFLResourceNodeSubsystem.cpp#L67[KBFLResourceNodeSubsystem]

end TODO:

== Required Changes

In addition to any specific-to-your-mod issues you may encounter,
the changes described below _must_ be made in order for your mod to be updated.

=== Dependency Updates

The following project dependencies have updated.
Install the updated versions as you follow the xref:Development/UpdatingToNewVersions.adoc[Updating your Mod] guide.

==== Engine Update

Satisfactory 1.2 brings the game to Unreal Engine 5.6.1.
Download and set up our custom release while following the
xref:Development/UpdatingToNewVersions.adoc[Updating your Mod guide].

==== Clang Toolchain Update

This updated engine version also requires an updated clang toolchain.
Download and set up the new toolchain while following the
xref:Development/UpdatingToNewVersions.adoc[Updating your Mod guide].

==== Wwise Update

CSS has also updated to a newer version of Wwise.
The xref:Development/BeginnersGuide/dependencies.adoc#_wwise[Dependencies page Wwise instructions]
lists the new Wwise version and guides you through integrating it into your project as you follow the
xref:Development/UpdatingToNewVersions.adoc[Updating your Mod guide].

=== Generate Wwise Sound Banks

If you see the "GeneratedSoundBanks folder does not seem to be set. Would you like to open the settings window to set it?" message, use the Wwise editor to
xref:Development/BeginnersGuide/project_setup.adoc#Wwise_GenerateBanks[manually generate sound banks once],
You should not need to do this again unless you create a new Wwise project or use Wwise systems in your mod.

== Additional Changes

You might not be affected by these changes,
but we'd like to draw extra attention to them.

=== Asset Dumping with `-nullrhi` no longer works
Dumping assets with `-nullrhi` is no longer possible, because Unreal Engine doesn't load mesh data when using that anymore, 
as a dedicated servers memory optimization. 

`-RenderOffscreen` can be used instead, which will still use the GPU to render, but without the game window.

TODO: Add any additional changes that we want to draw attention to here.

== Complete Changelog

[NOTE]
====
This link temporarily compares to the `dev` branch since there is no 3.12 tag until release.
====

The full list containing every changed file and asset can be viewed using GitHub's Compare Changes feature:
// https://github.com/satisfactorymodding/SatisfactoryModLoader/compare/v3.11.3...v3.12.0
https://github.com/satisfactorymodding/SatisfactoryModLoader/compare/v3.11.3...dev