= Installing Mods on Dedicated Servers

[IMPORTANT]
====
If you're seeing this message, that means this page is not complete yet!
This warning will be removed once dedicated server support is actually complete.
Expect mistakes and inaccuracies until then.
====

TODO write this page (it's hidden from the sidebar for now)

== Install the Vanilla Server

The first step is to obtain a copy of the vanilla dedicated server.
The Satisfactory Official Wiki already has a
https://satisfactory.wiki.gg/wiki/Dedicated_servers[detailed guide covering how to do this].

== Install Ficsit-CLI

This can be installed either on your own computer, used to manage the files remotely,
or on the server computer itself.

https://github.com/satisfactorymodding/ficsit-cli

ficsit-cli allows network locations (ex. `//192.168.1.42/appdata/satisfactory`)
and FTP locations to be listed as installs (ex. `ftp://user:password@host/path`)

Note that when applying changes in ficsit-cli, changes will be applied to all installations it's aware of in parallel (installations can be on separate profiles) (TODO find a better way to explain this)

== Import a Profile Created in SMM

Although it is possible to use ficsit-cli to manage the install and create profiles,
this is not recommended as you could end up with a mismatch between client and server mod versions,
preventing you from connecting.

Create a profile on your own computer with the xref:ForUsers/SatisfactoryModManager.adoc[Mod Manager]
and use its Export Profile functionality to produce a file that can be imported into ficsit-cli.

== Configuring Mods on Servers

There is not currently an interface for adjusting mod configurations remotely on dedicated servers.
As a result, you should configure mods client side and copy the config files over to the server.

Note that some mods could stop working correctly if client and server configs don't match.

Check the xref:faq.adoc#Files_ModConfig[FAQ on where game files are located] to see where config files are stored.

== Third Party Server Hosts

TODO Can we expect them to have ficsit CLI installed?
Tell people to follow the server provider's instructions for installing mods.
