= C++ Modding

Utilizing {cpp} code in your mod allows access to a much wider variety of game systems and features.
Furthermore, {cpp} code is often compiled into far more performance friendly code than its Blueprint equivalent.

However, {cpp} systems have their own shortcomings as well.
Writing a mod with {cpp} does not mean replacing all of your Blueprint assets with {cpp} code.
The best mods are implemented with a careful combination of both {cpp} and Blueprint code.

== Understanding Blueprint vs C++

Alex Forsythe has an excellent writeup (and corresponding video)
that explains the different roles of {cpp} and blueprint in an Unreal project.
Alex's summary of the article:

====
It's not an either/or decision.
Learn what makes C++ and Blueprints different, what they have in common, and how to use them together effectively.
====

You can find the article (and a link to the video) http://awforsythe.com/unreal/blueprints_vs_cpp/[here].
You should at the very least watch the video before proceeding.
Reading the article is also highly recommended.

== Requirements

Well, since this is a very advanced topic, we recommend you to learn {cpp}
and {cpp} for Unreal Engine first.

We have compiled a list of some helpful learning resources xref:Development/index.adoc#_resources[here], but you will probably want to search out some more on your own.

Here is a list of some concepts you should learn before going further:

{Cpp} specific:

* If/Else
* Loop Structures
** While
** For
** For Each
* Lambda Functions
* Pointers
* References

{Cpp} concepts which are used but are implemented differently in Unreal Engine:

- std::string
- std::vector
- std::set (And the differences between it and std::vector)
- Smart Pointers

The Unreal Engine synonyms for the aforementioned concepts (the UE implementation of them):

- std::string -> FString
- std::vector -> TArray
- std::set -> TSet
- std::(unordered_)set<T> -> TSet<T>
- std::(unordered_)map<K, V> -> TMap<K, V>
- Unreal Smart Pointers

Other stuff added only by UE or general programming concepts:

- What a UObject/UProperty/UFunction (reflection system) is
- What an AActor is
- What garbage collection means, how it works, and how to make use of it

If you have a good understanding of most these concepts, then you have a very solid foundation from which to start modding. If so, this is likely not your first time working on a project or mod like this, and you'll be able to judge what content you can skip over and learn when needed.

We can not understate the value of learning through doing. Especially if just starting out with these concepts, we suggest that instead of immediately beginning working on a mod, taking the time to make a separate Unreal {cpp} project for testing and practice. Try out working with the concepts mentioned above before trying to make use of them in a mod.

The following resources may be helpful for you in the creation of your {cpp} mods:

* CSS has been kind enough to provide us with the Satisfactory {cpp} headers.
  They are already included in the Starter Project,
  but are originally pulled from the `CommunityResources` folder of your install.
* You can find the `.pdb` files for the game in your install's Binaries folder.

== Dll, pdb & more

When you compile your {cpp} code into the final binaries (stuff that actually is used by the game)
you will get a Dynamic Link Library (`.dll`) file.
This file comes with a companion, the Program Database (`.pdb`) file.
This file holds additional information about the original source code and allows you to debug your code more easily in runtime.
Alpakit Release automatically handles the compilation and packaging of these files for different platforms for you.
More info on the upload process can be found on the xref:UploadToSMR.adoc[Uploading to SMR page].

We won't go into detail about the general technical stuff aspects of {cpp} in this documentation.
If you want to learn more about that, there are plenty of good resources available elsewhere on the Internet.
In order to write {cpp} mods, you will require both general {cpp} knowledge, and knowledge about how {cpp} applies to Unreal Engine systems.
You can find a quick guide to the Unreal portion in the https://docs.unrealengine.com/en-US/Programming/Introduction/index.html[Unreal Documentation].

== Modding Capabilities

As Satisfactory is packaged as a modular build and the developers distribute the headers and `pdb`s for us,
and mods are loaded as Unreal plugins,
there is very little of the game that {cpp} mods _can't_ modify.
It usually just comes down to how much patience you have to figure out how to do it.

If you experience a crash or some undefined behavior while using a function from Unreal Engine or Satisfactory,
you should read the doc comment that has been added to the function.
Sometimes the comment will tell you that it doesn't work
and suggest you use the workaround written in the comment,
or it may contain valuable context about how the function can be used.

If it still doesn't work, and you are **absolutely sure** that you are using it correctly,
contact the SML developers on the Discord for further advice.
