= Getting Started

In this section, we will cover a variety of topics about making models and visuals for Satisfactory mods.
It is essential you have a modding environment and working mod to test you changes. If you don't, go and follow the xref:Development/BeginnersGuide/index.adoc[Beginners Guide].

== Basic Theories

While we're not going to teach you how to model, that's too big of a concept to fit in these docs, but if you're just getting started try some intro to Blender tutorials before continuing further.

Even if you do know how to model there may be some concepts/processes the game is using you might want to lookup/practice. Below is a list of some major technologies or techniques you should at least be aware of.

* {blank}
+
Weighted Vertex Normals::
  Save triangles and make you mesh look good. Very important for mechanical or hard surface models.
  Used extensively on all buildable objects.
  https://www.youtube.com/watch?v=sqGFhiP-2mc[Youtube explanation]
* {blank}
+
PBR Materials::
  Use a collection of textures together to better represent metal vs plastic vs rock etc.
  There's many tools to help create PBR textures like Substance or Quixel.
  https://academy.substance3d.com/courses/the-pbr-guide-part-1[Indepth Article]
* {blank}
+
Texture Atlases::
  Helps understand the painting system (which allows you to change factory colours) and allows you to use decals on your models.
  https://blog.immersed.team/texture-atlasing-an-inside-look-at-optimizing-3d-worlds-8a07145856d7[Tutorial Article]
* {blank}
+
Normal Map Decals::
  Exceptionally important for adding extra details without adding massive triangle counts.
  https://www.youtube.com/watch?v=66IGMnPgEW0[Youtube walkthrough]
* {blank}
+
Lightmap UVs::
  Give every portion of the mesh unique surface area so that lighting calculations can save information to the right spots without issues.
  https://www.youtube.com/watch?v=UnUn4nRoh-E[Youtube Example]
* {blank}
+
Ambient Occlusion Bake::
  Help the lighting engine do a better job by making a texture to describe where the nooks, crannies, and edges of meshes are.
  https://www.katsbits.com/tutorials/blender/baking-ambient-occlusion.php[Tutorial Article]

== Help
Keep in mind these are common techniques and many more resources are available to learn from. Feel free to ask for help in the `+#help-making-mods+` channel on the https://discord.gg/xkVJ73E[Discord server] or in the https://forums.ficsit.app/[SMR Forums]


