= Satisfactory Style
If you're trying to get a handle on the Satisfactory visual style for custom and new assets and want some pointers then keep reading.

== Industrial Sci-Fi
Satisfactory's style sits in a bit of a greyzone on the edge of popular styles like CyberPunk.
Similar to Cyberpunk its futuristic, impersonal, detailed, industrial, and fits well with Brutalism.
But it shares many traits with styles like SteamPunk where it focuses on designs and mechanisms that should of been supplanted by new technology.
It's using similar approaches where it extrapolates how more modern ideas may be implemented with older designs.
Everything is quite bright, clean, and well maintained though, more similar to steampunk than the dirt of cyberpunk.
Often parts of Cyberpunk designs are the complete immersion in digital life and neon signs in the sky.
Satisfactory explicitly shuns many of these Sci-Fi tropes and styles.
Note the general absence of lasers, holograms, plasma, lumifibre, and digital things.
While present in vehicle paths, build gun, xeno-basher, ADA, etc. They are not used in the majority of the buildings, items, and their designs.
Even when digital things surface they're given an older or less sophisticated flair, like a Windows XP desktop background, or obvious text to speech synthesis.
At every opportunity Satisfactory focuses on industrial designs, machines, and mechanisms of the 90's to 00's when they were new and cool.
While it embraces Sci-Fi it keeps a leash on it to prevent it from running away into energy beams and warp drive.
It's a style of Industrial Sci-Fi Retro Futurisism that asks, what if heavy industry could of landed on other planets in the 90's.

== Technical implementation
Due to the sheer number of elements the game intends to display technical implementation feeds back into visuals.
The strong corporate presences of Ficsit allows for very modular, colourful designs while retaining performance.
The concept of Brand Identity extending to every machine and the Brand being loud and proud enables this.
Deferred rendering decal systems like medium polygon objects reused and limited texture sources to pull decals from.
Embracing a corporate and modular design leans into these technical limitations allows for style and performance.
Further medium poly approaches excel at large complex areas with physical details or spots of interest.
This matches up exactly with the look large industrial machines with panels and warning labels often present.

== Case Studies
Without the authors original notes its often helpful to work backwards from their final decisions, this section is for a few deep dives of specific choices.

=== Train System
The train system's visual design in Satisfactory clearly demonstrates the aesthetic choices being made and how to mix in Sci-Fi into 90s industrial.
When choosing a design for trains there are a lot of types to choose from, diesel trains are synonymous with heavy industry and the inspiration is clear.
So rather than anything like a Maglev, or Electric train design the final design is heavily reminiscent of diesel locomotives, despite being electric in game.
Further, it's more similar to the 90's and 00 era of design than even other angular designs.
More modern and older designs both feature more gradual curves, and/or more plain undetailed space.
While better for efficiency or implying futuristic functions the angular 90's design was prioritized.
Unfortunately and entirely normal diesel locomotive would look out of place and require fuel.
Taking some of the back planar areas of the train and adding in Classic glowing Sci-Fi engines helps modernize the design.
Importantly though, the glowing engines do not fit neatly inside the machine.
They push the silhouette out giving it interest and shape, but also making the more cutting edge parts look less refined.
Interestingly after shunning many Maglev and monorail train shapes, because of their modern design, the design of the rails is brought back.
This more modern rail design and the Sci-Fi engine help solidify the train into the future while essentially being from the 90's.
This balance of futuristic and past styles is where Satisfactory is best represented.