= Satisfactory Acronym Vault (SAV)

This page exists to helps remember the excessive amount of acronyms used in our community.

Originally a
https://github.com/satisfactorymodding/SatisfactoryAcronymVault[GitHub repository of its own],
it has been merged with the docs.

Feel free to suggest changes on our Discord, or pull request them (Edit This Page in the top right), to help keep this page up to date.

== In-Use Acronyms

These acronyms are still actively in use.

=== Coffee Stain Studios (CSS)

_Not_ https://www.w3.org/Style/CSS/Overview.en.html[cascading style sheets].

https://www.coffeestainstudios.com/[Coffee Stain Studios]
is the Swedish game studio that created Satisfactory.

=== Satisfactory Mod Loader (SML)

SML is a community-created mod that provides
an easy way for other mods to register content,
interface with the game, offer user-facing configuration options, and more.

Ironically, SML has changed so much since its creation that it is no longer responsible for loading mods.
Thanks to the helpful folks at CSS, mods are now Unreal Engine plugins,
and no longer require any special injection code to load.

Although it is possible to create a mod that does not depend on SML, they are very uncommon, as there are few reasons to do so.

Its public source code can be found on
https://github.com/satisfactorymodding/SatisfactoryModLoader[GitHub].

=== Satisfactory Mod Repository (SMR) aka ficsit.app

https://ficsit.app[ficsit.app], also known as the Satisfactory Mod Repository or FICSIT Augmentation Database, is the website at which mods, this documentation, guides, and more are hosted.

You can find the source code for the 
https://github.com/satisfactorymodding/smr-frontend[frontend]
and https://github.com/satisfactorymodding/smr-api[backend]
on their respective GitHub repositories.

=== Satisfactory Mod Manager (SMM)

Satisfactory Mod Manager handles all the steps of installing mods in Satisfactory for you!
It works closely with SMR to function.
SMM is only responsible for downloading the mods - it has no presence in a running game. SML is responsible for loading mod files at runtime.

Its public source code can be found on
https://github.com/satisfactorymodding/SatisfactoryModManager[GitHub].

=== Satisfactory Modding Documentation (SMD)

The documentation you're currently looking at!

=== Satisfactory Save Editor (SSE)

This name, and acronym, has been claimed by a number of save editor tools. It is most often used when referring to Goz3rr's editor

* https://github.com/Goz3rr/SatisfactorySaveEditor[Goz3rr's editor]
* https://cable.ayra.ch/satisfactory/editor.php[AyrA's editor]

=== Satisfactory Calculator and Interactive Map (SCIM)

https://satisfactory-calculator.com/[Satisfactory Calculator and Interactive Map]
is a tool made by Anthor,
and allows designing production lines, performing some save editing operations, and much more.

The https://github.com/AnthorNet/SC-ProductionPlanner[Production Planner]
and https://github.com/AnthorNet/SC-InteractiveMap[Interactive Map]
portions each have their own GitHub repositories.

=== Satisfactory Calculator BluePrints (SCBP)

link:#_satisfactory_calculator_and_interactive_map_scim[SCIM]
also features a https://satisfactory-calculator.com/en/blueprints[Blueprint Repository]
which allows sharing Blueprints created by the Blueprint Designer introduced in Update 7. These blueprints can be downloaded and placed in the
https://satisfactory.wiki.gg/wiki/Blueprint_Designer#Blueprint_Files[respective folder]
to be used in-game.

A separate https://satisfactory-calculator.com/en/megaprints[Megaprints Repository] is also available which contains larger blueprints that can only be created and used within SCIM.

=== Satisfactory Server Manager (SSM)

Satisfactory Server Manager is a webpage
designed to manage and control multiple satisfactory dedicated server instances.

Its public source code can be found on
https://github.com/mrhid6/SatisfactoryServerManager[GitHub].

=== Frequently Asked Questions (FAQ)

A list of questions that are frequently asked,
and common answers to them.

You can find the Satisfactory Modding Community's FAQ
xref:faq.adoc[on its respective docs page].

=== FICSIT Augmentation Database (FAD)

See link:#_satisfactory_mod_repository_smr_aka_ficsit_app[Satisfactory Mod Repository].
The mod repository is no longer frequently referenced by this name - one could say that doing so was a https://www.merriam-webster.com/dictionary/fad[FAD].

=== Too Many Acronyms (TMA)

Used to summarize the https://discord.com/channels/555424930502541343/555516979260293132/1034938314018525275[abundance] of Satisfactory Modding acronyms.

== Outdated Acronyms

These acronyms, for one reason or another, are no longer in use.
They are kept here for historical purposes.

* SMB = https://github.com/satisfactorymodding/SatisfactoryModBootstrapper[Satisfactory Mod Bootstrapper] (Obsoleted by SML improvements)
* SPL = Satisfactory Pak Loader (Merged into SML)
* BPI = Blueprint Interface (Merged into SML)
* SBL = Satisfactory Blueprint Library (Merged into SML)
* SPM = Satisfactory Pak Modding (General term for pak modding)
* SID = https://github.com/satisfactorymodding/SatisfactoryItemDictionary[Satisfactory Item Dictionary] (Outdated)
* SMI = Satisfactory Mod Injector (Obsoleted by SML improvements)

