= Dependencies

To get started with modding of satisfactory you'll need multiple other
pieces of software downloaded and set up first.

* Satisfactory
* Unreal Engine 4 (v4.21)
* Visual Studio >= 2015
* Visual C++ 15
* Wwise
* Satisfactory Mod Loader (`+xinput1_3.dll+`)

[TIP]
====
If you want to code something in C++, you'll also need the Satisfactory
Mod Loader source code, which can be found
https://github.com/satisfactorymodding/SatisfactoryModLoader[here].
====

Don't worry, we'll guide you through each step of downloading and
installing these dependencies.

== Satisfactory

This should be pretty straightforward. Simply buy, download, and install
Satisfactory from the Epic Games Launcher. Launch the game to ensure all
files get set up correctly.

[TIP]
====
You should *not* use the Experimental version of the game. Although you
can make mods for the experimental version, this branch changes more
often and you'll likely need to edit your mod more often to stay up to
date with this version.
====

== Unreal Engine 4

This is much easier than you might think. Again, just go into the Epic
Games Launcher and then select the Unreal Engine tab at the left-hand
side of the launcher. Then click on the Download button in the upper
right-hand corner. A window should pop-up and ask you what version you
want to download. Select the current engine version of Satisfactory,
4.21. Also, remember to select your desired installation folder.

[WARNING]
====
Unreal Engine 4 is quite a large download, especially if you want to
install the source and the debug code. Keep this in mind in case you
want to move the install location later.
====

== Visual Studio

Visit the https://visualstudio.com/[Visual Studio] website and select
`+Community+` under `+Visual Studio-IDE+`/`+Download Visual Studio+`,
then download the installer. Now when you opened it, click again on
Visual Studio Community and keep the default settings. Hit Install and
wait for the installation process to finish.

== Visual C++ 15

This step is only required for users of Visual Studio 2019, since Visual
Studio 17 should already have this installed. Open the Visual Studio
installer again and click on the `+change+` button of your installation.
If not already selected, select `+Desktop development with C+\++`. Now
open the sidebar on the right-hand side and select under
`+Desktop development with C+++` the option `+VS 2015 C++-Buildtools+`.
Hit save and wait for the installation process to finish.

[TIP]
====
If the automatic installer doesn't work, you can find the manual
download
https://www.microsoft.com/de-de/download/details.aspx?id=48145[here from
Microsoft].
====

== Wwise

Visit https://wwise.com/[Wwise.com] and click on the `+Get Wwise+` ->
`+download Wwise+` button in the upper right corner. Now the website
should ask you to log in. Click on `+Sign in+` and follow the given
steps. After you finished downloading Wwise, open the installer and
start with installing the WWise launcher.

== Satisfactory Mod Loader

This step is extremely straight forward. Just visit
https://ficsit.app/[ficsit.app], open up the menu and click on SML in
the sidebar. Download the SML version you want your mod to use, we
recommend always the newest one, move the downloaded `+xinput1_3.dll+`
file into your Satisfactory installation folder under
`+Binaries/Win64+`, and you're done!
Note: You don't have to do this with the latest versions of SMM.
