= Unreal Learning Resources

Although this documentation site covers many aspects of modding Satisfactory,
there is a lot of core Unreal Engine knowledge that you must acquire on your own from other tutorials.
This page contains a list of some of those other tutorials.

Entries with a 📖 are primarily written, 📽 have a video component, and ⭐ are the ones we find especially useful and informative.

== Disclaimer: Satisfactory Could Be Different

Because Satisfactory is an established Unreal Engine game with its own systems,
there are a lot of Unreal Engine systems you don't need to worry about
Coffee Stain has already implemented them.

Furthemore, some Unreal concepts do not carry over to Satisfactory because
Coffee Stain has implemented their own systems instead.
The most obvious example of this are machines and the lightweight buildable system -
any buildings you create should use the optimized systems provided by Coffee Stain
wherever possible instead of trying to implement your own.

Some tutorials can't be followed in the Satisfactory Unreal project because
they rely on Play-in-Editor (PIE) functionality that the project lacks code for.
You'll have to install a separate copy of Unreal Engine 5 and create a separate project to follow those.

Keep this in mind as you follow other tutorials.

[id="UnrealEditor"]
== Using the Unreal Editor

* ⭐📖 https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-terminology?application_version=5.3[Unreal Engine Terminology] - 
  A glossary of common Unreal Engine terms you may encounter in other tutorials.

include::./../_includes/editor-familiarize-list.adoc[]

* ⭐📖 https://dev.epicgames.com/documentation/en-us/unreal-engine/reference-viewer-in-unreal-engine?application_version=5.3[Reference Viewer] -
  Using the Reference Viewer to see what assets reference a given asset, and what other assets are referenced by it.

* 📖 https://dev.epicgames.com/documentation/en-us/unreal-engine/property-matrix-in-unreal-engine?application_version=5.3[Property Matrix] -
  Quickly viewing or editing the properties of multiple assets at once using the Property Matrix.

* 📖 https://dev.epicgames.com/documentation/en-us/unreal-engine/global-asset-picker-in-unreal-engine?application_version=5.3[Global Asset Picker] -
  Quickly opening an asset you already know the name of using the Global Asset Picker.

[id="UnrealBlueprint"]
== Blueprint Scripting

* ⭐📖 https://dev.epicgames.com/documentation/en-us/unreal-engine/introduction-to-blueprints-visual-scripting-in-unreal-engine?application_version=5.3[Introduction to Blueprints] -
  A very high-level overview of what Blueprints are and what they can do.
  Links to other pages with more information about specific features.

  ** 📖 https://dev.epicgames.com/documentation/en-us/unreal-engine/basic-scripting-with-blueprints-in-unreal-engine?application_version=5.3[Basic Scripting with Blueprints] -
      Brief introduction to blueprint variables and event graphs

  ** 📖 https://dev.epicgames.com/documentation/en-us/unreal-engine/overview-of-blueprints-visual-scripting-in-unreal-engine?application_version=5.3[Blueprints Visual Scripting Overview] -
      Breaks down the anatomy of a Blueprint and the different types of Blueprints available.

  ** ⭐📖 https://dev.epicgames.com/documentation/en-us/unreal-engine/graph-editor-for-the-blueprints-visual-scripting-editor-in-unreal-engine?application_version=5.3[Blueprint Editor: Graph Editor] -
  Information on the Blueprint graph editor interface and the available interactions/keybinds.

* ⭐📖 https://dev.epicgames.com/documentation/unreal-engine/blueprint-foundations?application_version=5.3[Blueprint Foundations] - 
  Goes into more detail than "Introduction to Blueprints" and showcases how to use some of the editor features to edit them.

* ⭐📖 https://dev.epicgames.com/documentation/en-us/unreal-engine/blueprint-tutorials-in-unreal-engine?application_version=5.3[Blueprint Tutorials] -
  Links to walkthroughs of accomplishing various tasks in the Blueprint scripting editor.
  Note that the page currently duplicates all available tutorials in each complexity heading.

* 📖 https://dev.epicgames.com/documentation/en-us/unreal-engine/searching-in-blueprints-in-unreal-engine?application_version=5.3[Blueprint Search]
  How to use the Blueprint editor's search functionality.

* 📖 https://dev.epicgames.com/documentation/en-us/unreal-engine/graphs-in-unreal-engine?application_version=5.3[Anatomy of a Blueprint : Graphs] -
  Overview of the different kinds of blueprint graphs with links to additional information.

[id="UnrealCpp"]
== Unreal {cpp} 

* ⭐📖📽 https://www.youtube.com/watch?v=VMZftEVDuCE[Blueprints vs. C++: How They Fit Together and Why You Should Use Both]- 
  Excellent overview of how a project using both Blueprints and {cpp} can best leverage the strengths of both.

* 📖 https://dev.epicgames.com/documentation/en-us/unreal-engine/programming-with-cplusplus-in-unreal-engine?application_version=5.3['Programming with C++ in Unreal Engine' section] -
  Epic's primary {cpp} documentation hub containing many other articles.

  ** ⭐📖 https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-cpp-quick-start?application_version=5.3[Unreal Engine {cpp} Quick Start] -
  Epic's introductory tutorial for creating an actor in exclusively {cpp}. It's a cube that bobs up and down in the game level.

  ** ⭐📖 https://dev.epicgames.com/documentation/en-us/unreal-engine/epic-cplusplus-coding-standard-for-unreal-engine?application_version=5.3[Coding Standard for Unreal Engine] -
  Important details and conventions to be aware of when reading and writing {cpp} code for Unreal Engine.
  Notable points include an explanation of the T/U/A/F/I/E prefixes for names.

  ** 📖 https://dev.epicgames.com/documentation/en-us/unreal-engine/reflection-system-in-unreal-engine?application_version=5.3['Unreal Engine Reflection System' section] -
  Details many Unreal core constructs and macros (UObject, UProperty, etc.) backed by the reflection system that enable Unreal's editor and memory management features.

  ** 📖 https://dev.epicgames.com/documentation/en-us/unreal-engine/quick-start-guide-to-variables-timers-and-events-in-unreal-engine-cpp?application_version=5.3[Variables, Timers, and Events] -
  Working with timers and latent actions is generally easier in blueprint, but is possible in {cpp} as well.

* 📽 https://www.youtube.com/watch?v=IaU2Hue-ApI[The Unreal Engine Game Framework: From int main() to BeginPlay] -
  A high-level tour of what Unreal is doing under the hood when you run a game.

* ⭐📖 https://unreal-garden.com/[Unreal Garden (previously ben🌱ui)] -
  Community-ran documentation site with information on various topics, notable of which is extensive information on Unreal Metadata Specifiers.

  ** 📖 https://unreal-garden.com/docs/uclass/[All UCLASS Specifiers]
  ** 📖 https://unreal-garden.com/docs/ufunction/[All UFUNCTION Specifiers]
  ** 📖 https://unreal-garden.com/docs/uproperty/[All UPROPERTY Specifiers]

[id="General"]
== General

// cspell:ignore Sensei
* 📽 https://www.youtube.com/watch?v=k-zMkzmduqI[Unreal Sensei: Unreal Engine 5 Beginner Tutorial - UE5 Starter Course] -
  A walkthrough of creating an Unreal landscape level from scratch.
  Note that this tutorial will cover a lot of concepts and systems that Satisfactory already does for you.
* 📖📽 https://dev.epicgames.com/community/unreal-engine/learning[Learn Unreal Engine Portal] - 
  Collection of learning resources created by Epic Games and the Unreal developer community.

* 📽 https://www.youtube.com/c/AlexForsythe[Alex Forsythe] -
  YouTube channel that explains Unreal Engine systems and concepts (both Blueprint and {cpp}) in an approachable way,
  including replication.

* 📽 https://www.youtube.com/channel/UCOVfF7PfLbRdVEm0hONTrNQ[Mathew Wadstein] -
  YouTube channel with short, focused videos on specific Unreal Engine concepts.

* 📽 https://www.youtube.com/channel/UCz-eYJAUgSE-mqzKtit7m9g[Tinkr Academy/Virtus Learning Hub]
  YouTube channel with beginner-focused general Unreal tutorials and walkthroughs.

// This appears to be paid only now
// * http://academy.unrealengine.com/[Unreal Engine Academy]
//   A neat learning platform made by Epic Games for learning Unreal Engine.
