= You're Cloning the Starter Project

You've chosen to clone the Starter Project repository.
Good choice! This will make it easy to update the project with changes to SML later.

The below box will help you decide which repository branch to clone.
It's imperative that you download the correct Starter Project version of the game you're modding
or you will have to repeat some of the setup process again.

== What is Cloning?

If you aren't familiar with version control software (VCS) like Git,
check out our xref:Development/BeginnersGuide/LearnGit.adoc[mini tutorial] that will cover the basics.

== What Branch to Clone

// When updating the below, remember to update StaterProjectViaClone.adoc, StarterProjectViaZip.adoc, and dependencies.adoc (engine)
====
This is the *latest stable* version of the docs.
// This is the *development* version of the docs.

// Stable (Release) and Experimental are currently both the same version - 1.0 Release.

Clone the **`master` branch** to develop a mod for the stable version of SML.
// You should clone the **`dev` branch** because SML 3.8.? is not released yet.

// You should clone either the **`dev` branch** or the **`master` branch**.
// Of those two, you probably want whichever branch was pushed to most recently, which you can see
// https://github.com/satisfactorymodding/SatisfactoryModLoader/branches[on the GitHub repository].

If you're uncertain about which branch to clone, **ask us on the Discord**.
====

https://github.com/satisfactorymodding/SatisfactoryModLoader/[Here]
is a link to the GitHub page of repository to clone.
Get the clone URL via the **`<> Code`** dropdown button on the GitHub page.

If you just followed the xref:Development/BeginnersGuide/LearnGit.adoc[mini git tutorial],
we suggest following the steps
https://docs.github.com/en/desktop/adding-and-cloning-repositories/cloning-a-repository-from-github-to-github-desktop[here]
to use GitHub Desktop to clone the repository.
Otherwise, use the git clone method of your choice.

Your Git client will probably start you on the `master` branch by default,
so you may have to switch branches to the branch you actually intended to clone.

You can move the cloned repository folder later, and you can name it whatever you'd like.
Make sure to read the notes on the
xref:Development/BeginnersGuide/StarterProject/ObtainStarterProject.adoc[Starter Project page]
about good long-term homes for your starter project files.

The directory is ready for use as soon as the clone is complete
and you have switched to the branch you intend to use.

[IMPORTANT]
====
Many Git clients will automatically clone the repository's default branch.
Make sure it has actually cloned the branch you intended to before proceeding.
====

== Next Steps

Now that all the dependencies are installed, you can move onto
xref:Development/BeginnersGuide/project_setup.adoc[setting up the project].

