= Downloading a Zip

You've chosen to download a zip of the Starter Project repository.

The below box will help you decide which repository branch to download a zip of.
It's imperative that you download the correct Starter Project version
or you will have to repeat some of the setup process again.

== What Version to Download

// needed for :actionphrase:
include::../_includes/repo-versions.adoc[]

:verbphrase: download a zip of
:verbphraseCaps: Download a zip of
:actionphrase: {sp}from here: https://github.com/satisfactorymodding/SatisfactoryModLoader/archive/refs/heads/{suggested-branch}.zip
:archiveactionphrase: this tag: https://github.com/satisfactorymodding/SatisfactoryModLoader/archive/refs/tags/v{this-archive-version}.zip

include::../_includes/branch-notice.adoc[]

== Unzipping the Files

[WARNING]
====
By default, Windows marks files downloaded from the internet as "blocked".
You will run into problems later on because of this.
To get around this issue, right-click the zip file and "unblock" it from the Properties menu before unzipping it.
====

Unzip `SatisfactoryModLoader-master.zip` (or the `-dev.zip`) to get the Starter Project files.
If you're encountering issues extracting the zip,
try using another zip extracting software
such as https://www.7-zip.org/[7zip]
or https://www.win-rar.com/start.html[WinRAR].

You can move the directory later, and you can name the outermost folder whatever you'd like.

Make sure to read the notes on the
xref:Development/BeginnersGuide/StarterProject/ObtainStarterProject.adoc[Starter Project page]
about good long-term homes for your starter project files.

== Next Steps

Now that all the dependencies are installed, you can move onto
xref:Development/BeginnersGuide/project_setup.adoc[setting up the project].

