= Blueprint Library

The SML provides some blueprint function libraries allowing you to interact with the engine, satisfactory or the loader way more easily with blueprints.

== Logging

The mod loader provides a blueprint function library `Blueprint Logging Library` that exposes some logging features to blueprints.
This allows you to log things in different verbosity states.

If you want to log something in C++, pleas use unreal's default way of logging.
Preferly creation your own log category for your mod.

=== `LogInfo(String str, bool ignoreDebugMode)`
Logs the given string with the "info-color" but only
if debugMode of SML is enabled or ignoreDebugMode is set to true.

=== `LogVerbose(String str)`
Logs the given string in the "verbose-level".

=== `LogDisplay(String str)`
Logs the given string in the "display-level".

=== `LogWarning(String str)`
Logs the given string in the "warning-level".

=== `LogError(String str)`
Logs the given string in the "error-level".

=== `LogFatal(String str)`
Logs the given string in the "fatal-level".
Causes the game to crash.

== Config

The SBL also provides the ability to save and load configurations in Blueprints.

As `config` you can pass any kind of custom struct.
But only these types will get parsed properly:

- String
- Float
- Integer
- Bool
- other Structs
- Array of any of the above allowed types

=== `void SaveConfig(String modid, Struct config)`
Dumps the given config struct as a Json and saves it as the config file for the mod with the given name.
  
=== `void LoadConfig(String modid, Struct& config)`
Parses the config file of the given mod id to the attributes of the given config struct.
Attributes not existent in the config file won't get changed.
(basically if you set default values for the struct,
or just set the structs' variables to the values you want to use as default,
this would allow you to define default values for the config files)
Settings set in the config file which don't have a corresponding attribute in the config struct simply get ignored.

=== `void StructToJson(String& String, bool UsePrettyPropertyNames, Struct Structure)`
Converts the given structure to a string, storing it at the passed String address. If UsePrettyPropertyNames is true, the property names will look more human readable.

=== `void StructFromJson(String String, bool UsePrettyPropertyNames, Struct& Structure)`
Converts the given json String to a structure. Make sure that UsePrettyPropertyNames is enabled if it was enabled when producing the json via StructToJson.

== Blueprint Mod Loading Library

The `Blueprint Mod Loading Library` provides functions to interact with the modloading process.

=== `bool IsModLoaded(String ModReference)`
This function takes a xref:Development/BeginnersGuide/index.adoc#_mod_reference[mod reference] as input and checks
if any kind of mod with that reference got loaded or not.

=== `Array<String> GetLoadedMods()`
This function returns the xref:Development/BeginnersGuide/index.adoc#_mod_reference[mod references] of all currently loaded mods in an array.

=== `ModInfo GetLoadedModInfo(String ModReference)`
This function allows you to access additional information about the mod with the given reference.

=== `Texture2D LoadModIconTexture(String ModReference, Texture2D FallbackIcon)`
This function allows you to load the mod icon of the mod with the given reference as a Texture2D.
If no Texture or mod is found, the function will return the fallback icon.

=== `Version GetSMLVersion()`
This function allows you to retrieve the version of the currently installed mod loader.

=== `bool IsDevelopmentModEnabled()`
This function allows you to easily check if the SML development mode is activated.

=== `Map<Name, String> GetExtraModLoaderAttributes()`
Returns extra attributes exposed by the mod loader implementation.

== Version Library

The `Blueprint Version Library` provides a couple of functions that allow you to interact with the version system more easily and generally helps you out with some stuff.

=== `bool ParseVersionString(String String, out Version OutVersion, out String ErrorMessage)`
This function tries to create a FVersion object from the provided string.
Returns true if able to convert the string successfully and if not, sets the ErrorMessage accordingly.

=== `String Conv_VersionToString(FVersion Version)`
Converts the given version structure to a string.

=== `bool ParseVersionRangeString(String String, out VersionRange OutVersionRange, out String OutErrorMessage)`
Tries to convert the given string into a Version Range struct.
Returns true if it was able to do so, and if not, sets the error message accordingly.

=== `String Conv_VersionRangeToString(FVersionRange VersionRange)`
Converts the given version range structure to a string.

=== `bool Matches(VersionRange VersionRange, Version Version)`
Returns true if the provided version matches the given version range.

== FVersion

This struct contains information about a xref:https://semver.org/[SemVer] compatible version in a parsed state.

=== Member Fields

* int64 Major (read only)
+
The major SemVer version number
* int64 Minor (read only)
+
The minor SemVer version number
* int64 Patch (read only)
+
The SemVer patch number
* String Type (read only)
+
The version type of this SemVer version.
+
Can be:
+
** "alpha"
** "beta"
** "release"

* String BuildInfo (read only)
+
Additional information to the version build.

== FModInfo

This struct contains information about a loaded mod.
Mainly contents of the data.json of the mod.

=== Member Fields

- String ModId (read only)
+
The xref:Development/BeginnersGuide/index.adoc#_mod_reference[mod reference]
- String Name (read only)
+
The display name of the mod
- FVersion Version (read only)
+
The version of the mod
- String Description (read only)
+
The description of the mod
- Array<String> Authors (read only)
+
The names of the authors of the mod in a list.
- String Credits (read only)
+
Credits of the mod
