= Simple Construction Script (SCS) Hooks

Introduced in SML3.5, Blueprint Simple Construction Script hooks allow adding modded
https://docs.unrealengine.com/5.1/en-US/components-in-unreal-engine/[Components]
to any blueprint-based actor.

Mods can define Blueprint SCS in their
xref:Development/ModLoader/ModModules.adoc#_game_instance_bound_module_ugameinstancemodule[Game Instance Module].

This system is very flexible and it is difficult to summarize its capabilities.
Here are some example usages:

* Spawn a component on the player character that does some custom logic
    ** Example Mod uses this to add a hat to the player if they have an Example Item in their inventory.
       Note that the component is always spawned, but custom logic controls if the hat is visible to the player.
* Easily track (and potentially store with the save file) per-player data that is guaranteed to exist by hooking the construction of BP_PlayerState
    ** An example of this can be found in the open-source https://ficsit.app/mod/FreeSamples[Free Samples] mod.
