= Satisfactory Pak Loader

The SPL makes it possible that modders don't need to write a .dll mod to
initiate the mod loading.

== InitMod

`InitMod` is a special Actor which gets spawned in the boot-up process
of the map, so that you can f.e. register new items. The actors class
needs to be located in a specific folder in your project root. That
folder needs to have the exact name of the final pak you will deploy to
the users. f.e. if the pak you will deploy is called `DocMod_p.pak`
you're actors path needs to be `/Content/DocMod/InitMod`.

=== Init-Events

If not only want to use the constructor and begin play for doing stuff in the boot process.
You can let your class derive from `ASMLInitMod` were you can override the the `Init` and `PostInit` functions.

The ASMLInitMod also already provideds a basic shematic registering implementation.
That means you just need to add the shematics you want to register to the mSchematics array
and they will get registered automatically.

== Init Menu

`InitMenu` is nearly the same as `InitMod` just for the main menu.
The normal `InitMod` gets spawned when a normal gameplay session runs.
The `InitMenu` gets spawned and initialized in the main menu.

If we use the same example fron `InitMod` the `InitMenu` would be located in `/Content/DocMod/InitMenu`.

=== Init-Events

The provided basic class you eventually want to use is called `ASMLInitMenu` and provides
the `Init` function you can override to do some crazy stuff in the menu.